// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package transit_gateway_prefix_list_reference

import (
	"context"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/ec2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/ec2-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.EC2{}
	_ = &svcapitypes.TransitGatewayPrefixListReference{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.GetTransitGatewayPrefixListReferencesWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "GetTransitGatewayPrefixListReferences", respErr)
	if respErr != nil {
		if awsErr, ok := ackerr.AWSError(respErr); ok && awsErr.Code() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, respErr
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.TransitGatewayPrefixListReferences {
		if elem.Blackhole != nil {
			ko.Spec.Blackhole = elem.Blackhole
		}
		if elem.PrefixListId != nil {
			ko.Spec.PrefixListID = elem.PrefixListId
		}
		if elem.PrefixListOwnerId != nil {
			ko.Status.PrefixListOwnerID = elem.PrefixListOwnerId
		}
		if elem.State != nil {
			ko.Status.State = elem.State
		}
		if elem.TransitGatewayAttachment != nil {
			f4 := &svcapitypes.TransitGatewayPrefixListAttachment{}
			if elem.TransitGatewayAttachment.ResourceId != nil {
				f4.ResourceID = elem.TransitGatewayAttachment.ResourceId
			}
			if elem.TransitGatewayAttachment.ResourceType != nil {
				f4.ResourceType = elem.TransitGatewayAttachment.ResourceType
			}
			if elem.TransitGatewayAttachment.TransitGatewayAttachmentId != nil {
				f4.TransitGatewayAttachmentID = elem.TransitGatewayAttachment.TransitGatewayAttachmentId
			}
			ko.Status.TransitGatewayAttachment = f4
		}
		if elem.TransitGatewayRouteTableId != nil {
			ko.Spec.TransitGatewayRouteTableID = elem.TransitGatewayRouteTableId
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.GetTransitGatewayPrefixListReferencesInput, error) {
	res := &svcsdk.GetTransitGatewayPrefixListReferencesInput{}

	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}
	if r.ko.Spec.TransitGatewayRouteTableID != nil {
		res.SetTransitGatewayRouteTableId(*r.ko.Spec.TransitGatewayRouteTableID)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a new resource with any fields in the Status field filled in
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newCreateRequestPayload(ctx, r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.CreateTransitGatewayPrefixListReferenceWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateTransitGatewayPrefixListReference", respErr)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.TransitGatewayPrefixListReference.PrefixListOwnerId != nil {
		ko.Status.PrefixListOwnerID = resp.TransitGatewayPrefixListReference.PrefixListOwnerId
	}
	if resp.TransitGatewayPrefixListReference.State != nil {
		ko.Status.State = resp.TransitGatewayPrefixListReference.State
	}
	if resp.TransitGatewayPrefixListReference.TransitGatewayAttachment != nil {
		f4 := &svcapitypes.TransitGatewayPrefixListAttachment{}
		if resp.TransitGatewayPrefixListReference.TransitGatewayAttachment.ResourceId != nil {
			f4.ResourceID = resp.TransitGatewayPrefixListReference.TransitGatewayAttachment.ResourceId
		}
		if resp.TransitGatewayPrefixListReference.TransitGatewayAttachment.ResourceType != nil {
			f4.ResourceType = resp.TransitGatewayPrefixListReference.TransitGatewayAttachment.ResourceType
		}
		if resp.TransitGatewayPrefixListReference.TransitGatewayAttachment.TransitGatewayAttachmentId != nil {
			f4.TransitGatewayAttachmentID = resp.TransitGatewayPrefixListReference.TransitGatewayAttachment.TransitGatewayAttachmentId
		}
		ko.Status.TransitGatewayAttachment = f4
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateTransitGatewayPrefixListReferenceInput, error) {
	res := &svcsdk.CreateTransitGatewayPrefixListReferenceInput{}

	if r.ko.Spec.Blackhole != nil {
		res.SetBlackhole(*r.ko.Spec.Blackhole)
	}
	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}
	if r.ko.Spec.PrefixListID != nil {
		res.SetPrefixListId(*r.ko.Spec.PrefixListID)
	}
	if r.ko.Spec.TransitGatewayAttachmentID != nil {
		res.SetTransitGatewayAttachmentId(*r.ko.Spec.TransitGatewayAttachmentID)
	}
	if r.ko.Spec.TransitGatewayRouteTableID != nil {
		res.SetTransitGatewayRouteTableId(*r.ko.Spec.TransitGatewayRouteTableID)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	diffReporter *ackcompare.Reporter,
) (*resource, error) {

	input, err := rm.newUpdateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.ModifyTransitGatewayPrefixListReferenceWithContext(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyTransitGatewayPrefixListReference", respErr)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.TransitGatewayPrefixListReference.PrefixListOwnerId != nil {
		ko.Status.PrefixListOwnerID = resp.TransitGatewayPrefixListReference.PrefixListOwnerId
	}
	if resp.TransitGatewayPrefixListReference.State != nil {
		ko.Status.State = resp.TransitGatewayPrefixListReference.State
	}
	if resp.TransitGatewayPrefixListReference.TransitGatewayAttachment != nil {
		f4 := &svcapitypes.TransitGatewayPrefixListAttachment{}
		if resp.TransitGatewayPrefixListReference.TransitGatewayAttachment.ResourceId != nil {
			f4.ResourceID = resp.TransitGatewayPrefixListReference.TransitGatewayAttachment.ResourceId
		}
		if resp.TransitGatewayPrefixListReference.TransitGatewayAttachment.ResourceType != nil {
			f4.ResourceType = resp.TransitGatewayPrefixListReference.TransitGatewayAttachment.ResourceType
		}
		if resp.TransitGatewayPrefixListReference.TransitGatewayAttachment.TransitGatewayAttachmentId != nil {
			f4.TransitGatewayAttachmentID = resp.TransitGatewayPrefixListReference.TransitGatewayAttachment.TransitGatewayAttachmentId
		}
		ko.Status.TransitGatewayAttachment = f4
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.ModifyTransitGatewayPrefixListReferenceInput, error) {
	res := &svcsdk.ModifyTransitGatewayPrefixListReferenceInput{}

	if r.ko.Spec.Blackhole != nil {
		res.SetBlackhole(*r.ko.Spec.Blackhole)
	}
	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}
	if r.ko.Spec.PrefixListID != nil {
		res.SetPrefixListId(*r.ko.Spec.PrefixListID)
	}
	if r.ko.Spec.TransitGatewayAttachmentID != nil {
		res.SetTransitGatewayAttachmentId(*r.ko.Spec.TransitGatewayAttachmentID)
	}
	if r.ko.Spec.TransitGatewayRouteTableID != nil {
		res.SetTransitGatewayRouteTableId(*r.ko.Spec.TransitGatewayRouteTableID)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) error {

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return err
	}
	_, respErr := rm.sdkapi.DeleteTransitGatewayPrefixListReferenceWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteTransitGatewayPrefixListReference", respErr)
	return respErr
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteTransitGatewayPrefixListReferenceInput, error) {
	res := &svcsdk.DeleteTransitGatewayPrefixListReferenceInput{}

	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}
	if r.ko.Spec.PrefixListID != nil {
		res.SetPrefixListId(*r.ko.Spec.PrefixListID)
	}
	if r.ko.Spec.TransitGatewayRouteTableID != nil {
		res.SetTransitGatewayRouteTableId(*r.ko.Spec.TransitGatewayRouteTableID)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.TransitGatewayPrefixListReference,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
			break
		}
	}

	if rm.terminalAWSError(err) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		terminalCondition.Status = corev1.ConditionTrue
		awsErr, _ := ackerr.AWSError(err)
		errorMessage := awsErr.Message()
		terminalCondition.Message = &errorMessage
	} else if terminalCondition != nil {
		terminalCondition.Status = corev1.ConditionFalse
		terminalCondition.Message = nil
	}
	if terminalCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
