// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package main

import (
	"os"

	ackcfg "github.com/aws-controllers-k8s/runtime/pkg/config"
	ackrt "github.com/aws-controllers-k8s/runtime/pkg/runtime"
	flag "github.com/spf13/pflag"
	"k8s.io/apimachinery/pkg/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	ctrlrt "sigs.k8s.io/controller-runtime"
	ctrlrtmetrics "sigs.k8s.io/controller-runtime/pkg/metrics"

	svctypes "github.com/aws-controllers-k8s/ec2-controller/apis/v1alpha1"
	svcresource "github.com/aws-controllers-k8s/ec2-controller/pkg/resource"

	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/capacity_reservation"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/carrier_gateway"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/client_vpn_endpoint"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/client_vpn_route"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/customer_gateway"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/default_subnet"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/default_vpc"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/egress_only_internet_gateway"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/fleet"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/fpga_image"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/image"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/instance_export_task"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/internet_gateway"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/key_pair"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/launch_template"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/launch_template_version"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/local_gateway_route"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/local_gateway_route_table_vpc_association"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/managed_prefix_list"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/nat_gateway"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/network_acl"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/network_acl_entry"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/network_insights_path"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/network_interface"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/network_interface_permission"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/placement_group"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/reserved_instances_listing"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/route"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/route_table"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/security_group"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/snapshot"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/spot_datafeed_subscription"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/subnet"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/traffic_mirror_filter"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/traffic_mirror_filter_rule"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/traffic_mirror_session"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/traffic_mirror_target"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/transit_gateway"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/transit_gateway_connect"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/transit_gateway_connect_peer"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/transit_gateway_multicast_domain"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/transit_gateway_peering_attachment"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/transit_gateway_prefix_list_reference"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/transit_gateway_route"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/transit_gateway_route_table"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/transit_gateway_vpc_attachment"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/volume"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/vpc"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/vpc_endpoint"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/vpc_endpoint_connection_notification"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/vpc_endpoint_service_configuration"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/vpc_peering_connection"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/vpn_connection"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/vpn_connection_route"
	_ "github.com/aws-controllers-k8s/ec2-controller/pkg/resource/vpn_gateway"
)

var (
	awsServiceAPIGroup = "ec2.services.k8s.aws"
	awsServiceAlias    = "ec2"
	scheme             = runtime.NewScheme()
	setupLog           = ctrlrt.Log.WithName("setup")
)

func init() {
	_ = clientgoscheme.AddToScheme(scheme)
	_ = svctypes.AddToScheme(scheme)
}

func main() {
	var ackCfg ackcfg.Config
	ackCfg.BindFlags()
	flag.Parse()
	ackCfg.SetupLogger()

	if err := ackCfg.Validate(); err != nil {
		setupLog.Error(
			err, "Unable to create controller manager",
			"aws.service", awsServiceAlias,
		)
		os.Exit(1)
	}

	mgr, err := ctrlrt.NewManager(ctrlrt.GetConfigOrDie(), ctrlrt.Options{
		Scheme:             scheme,
		Port:               ackCfg.BindPort,
		MetricsBindAddress: ackCfg.MetricsAddr,
		LeaderElection:     ackCfg.EnableLeaderElection,
		LeaderElectionID:   awsServiceAPIGroup,
	})
	if err != nil {
		setupLog.Error(
			err, "unable to create controller manager",
			"aws.service", awsServiceAlias,
		)
		os.Exit(1)
	}

	stopChan := ctrlrt.SetupSignalHandler()

	setupLog.Info(
		"initializing service controller",
		"aws.service", awsServiceAlias,
	)
	sc := ackrt.NewServiceController(
		awsServiceAlias, awsServiceAPIGroup,
		ackrt.VersionInfo{}, // TODO: populate version info
	).WithLogger(
		ctrlrt.Log,
	).WithResourceManagerFactories(
		svcresource.GetManagerFactories(),
	).WithPrometheusRegistry(
		ctrlrtmetrics.Registry,
	)
	if err = sc.BindControllerManager(mgr, ackCfg); err != nil {
		setupLog.Error(
			err, "unable bind to controller manager to service controller",
			"aws.service", awsServiceAlias,
		)
		os.Exit(1)
	}

	setupLog.Info(
		"starting manager",
		"aws.service", awsServiceAlias,
	)
	if err := mgr.Start(stopChan); err != nil {
		setupLog.Error(
			err, "unable to start controller manager",
			"aws.service", awsServiceAlias,
		)
		os.Exit(1)
	}
}
