// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package transit_gateway

import (
	"context"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/ec2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/ec2-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.EC2{}
	_ = &svcapitypes.TransitGateway{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.DescribeTransitGatewaysWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeTransitGateways", respErr)
	if respErr != nil {
		if awsErr, ok := ackerr.AWSError(respErr); ok && awsErr.Code() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, respErr
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.TransitGateways {
		if elem.CreationTime != nil {
			ko.Status.CreationTime = &metav1.Time{*elem.CreationTime}
		}
		if elem.Description != nil {
			ko.Spec.Description = elem.Description
		}
		if elem.Options != nil {
			f2 := &svcapitypes.TransitGatewayRequestOptions{}
			if elem.Options.AmazonSideAsn != nil {
				f2.AmazonSideASN = elem.Options.AmazonSideAsn
			}
			if elem.Options.AutoAcceptSharedAttachments != nil {
				f2.AutoAcceptSharedAttachments = elem.Options.AutoAcceptSharedAttachments
			}
			if elem.Options.DefaultRouteTableAssociation != nil {
				f2.DefaultRouteTableAssociation = elem.Options.DefaultRouteTableAssociation
			}
			if elem.Options.DefaultRouteTablePropagation != nil {
				f2.DefaultRouteTablePropagation = elem.Options.DefaultRouteTablePropagation
			}
			if elem.Options.DnsSupport != nil {
				f2.DNSSupport = elem.Options.DnsSupport
			}
			if elem.Options.MulticastSupport != nil {
				f2.MulticastSupport = elem.Options.MulticastSupport
			}
			if elem.Options.TransitGatewayCidrBlocks != nil {
				f2f8 := []*string{}
				for _, f2f8iter := range elem.Options.TransitGatewayCidrBlocks {
					var f2f8elem string
					f2f8elem = *f2f8iter
					f2f8 = append(f2f8, &f2f8elem)
				}
				f2.TransitGatewayCIDRBlocks = f2f8
			}
			if elem.Options.VpnEcmpSupport != nil {
				f2.VPNEcmpSupport = elem.Options.VpnEcmpSupport
			}
			ko.Spec.Options = f2
		}
		if elem.OwnerId != nil {
			ko.Status.OwnerID = elem.OwnerId
		}
		if elem.State != nil {
			ko.Status.State = elem.State
		}
		if elem.Tags != nil {
			f5 := []*svcapitypes.Tag{}
			for _, f5iter := range elem.Tags {
				f5elem := &svcapitypes.Tag{}
				if f5iter.Key != nil {
					f5elem.Key = f5iter.Key
				}
				if f5iter.Value != nil {
					f5elem.Value = f5iter.Value
				}
				f5 = append(f5, f5elem)
			}
			ko.Status.Tags = f5
		}
		if elem.TransitGatewayArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.TransitGatewayArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.TransitGatewayId != nil {
			ko.Status.TransitGatewayID = elem.TransitGatewayId
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeTransitGatewaysInput, error) {
	res := &svcsdk.DescribeTransitGatewaysInput{}

	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a new resource with any fields in the Status field filled in
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newCreateRequestPayload(ctx, r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.CreateTransitGatewayWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateTransitGateway", respErr)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.TransitGateway.CreationTime != nil {
		ko.Status.CreationTime = &metav1.Time{*resp.TransitGateway.CreationTime}
	}
	if resp.TransitGateway.OwnerId != nil {
		ko.Status.OwnerID = resp.TransitGateway.OwnerId
	}
	if resp.TransitGateway.State != nil {
		ko.Status.State = resp.TransitGateway.State
	}
	if resp.TransitGateway.Tags != nil {
		f5 := []*svcapitypes.Tag{}
		for _, f5iter := range resp.TransitGateway.Tags {
			f5elem := &svcapitypes.Tag{}
			if f5iter.Key != nil {
				f5elem.Key = f5iter.Key
			}
			if f5iter.Value != nil {
				f5elem.Value = f5iter.Value
			}
			f5 = append(f5, f5elem)
		}
		ko.Status.Tags = f5
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.TransitGateway.TransitGatewayArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.TransitGateway.TransitGatewayArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.TransitGateway.TransitGatewayId != nil {
		ko.Status.TransitGatewayID = resp.TransitGateway.TransitGatewayId
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateTransitGatewayInput, error) {
	res := &svcsdk.CreateTransitGatewayInput{}

	if r.ko.Spec.Description != nil {
		res.SetDescription(*r.ko.Spec.Description)
	}
	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}
	if r.ko.Spec.Options != nil {
		f2 := &svcsdk.TransitGatewayRequestOptions{}
		if r.ko.Spec.Options.AmazonSideASN != nil {
			f2.SetAmazonSideAsn(*r.ko.Spec.Options.AmazonSideASN)
		}
		if r.ko.Spec.Options.AutoAcceptSharedAttachments != nil {
			f2.SetAutoAcceptSharedAttachments(*r.ko.Spec.Options.AutoAcceptSharedAttachments)
		}
		if r.ko.Spec.Options.DefaultRouteTableAssociation != nil {
			f2.SetDefaultRouteTableAssociation(*r.ko.Spec.Options.DefaultRouteTableAssociation)
		}
		if r.ko.Spec.Options.DefaultRouteTablePropagation != nil {
			f2.SetDefaultRouteTablePropagation(*r.ko.Spec.Options.DefaultRouteTablePropagation)
		}
		if r.ko.Spec.Options.DNSSupport != nil {
			f2.SetDnsSupport(*r.ko.Spec.Options.DNSSupport)
		}
		if r.ko.Spec.Options.MulticastSupport != nil {
			f2.SetMulticastSupport(*r.ko.Spec.Options.MulticastSupport)
		}
		if r.ko.Spec.Options.TransitGatewayCIDRBlocks != nil {
			f2f6 := []*string{}
			for _, f2f6iter := range r.ko.Spec.Options.TransitGatewayCIDRBlocks {
				var f2f6elem string
				f2f6elem = *f2f6iter
				f2f6 = append(f2f6, &f2f6elem)
			}
			f2.SetTransitGatewayCidrBlocks(f2f6)
		}
		if r.ko.Spec.Options.VPNEcmpSupport != nil {
			f2.SetVpnEcmpSupport(*r.ko.Spec.Options.VPNEcmpSupport)
		}
		res.SetOptions(f2)
	}
	if r.ko.Spec.TagSpecifications != nil {
		f3 := []*svcsdk.TagSpecification{}
		for _, f3iter := range r.ko.Spec.TagSpecifications {
			f3elem := &svcsdk.TagSpecification{}
			if f3iter.ResourceType != nil {
				f3elem.SetResourceType(*f3iter.ResourceType)
			}
			if f3iter.Tags != nil {
				f3elemf1 := []*svcsdk.Tag{}
				for _, f3elemf1iter := range f3iter.Tags {
					f3elemf1elem := &svcsdk.Tag{}
					if f3elemf1iter.Key != nil {
						f3elemf1elem.SetKey(*f3elemf1iter.Key)
					}
					if f3elemf1iter.Value != nil {
						f3elemf1elem.SetValue(*f3elemf1iter.Value)
					}
					f3elemf1 = append(f3elemf1, f3elemf1elem)
				}
				f3elem.SetTags(f3elemf1)
			}
			f3 = append(f3, f3elem)
		}
		res.SetTagSpecifications(f3)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	diffReporter *ackcompare.Reporter,
) (*resource, error) {

	input, err := rm.newUpdateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.ModifyTransitGatewayWithContext(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyTransitGateway", respErr)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.TransitGateway.CreationTime != nil {
		ko.Status.CreationTime = &metav1.Time{*resp.TransitGateway.CreationTime}
	}
	if resp.TransitGateway.OwnerId != nil {
		ko.Status.OwnerID = resp.TransitGateway.OwnerId
	}
	if resp.TransitGateway.State != nil {
		ko.Status.State = resp.TransitGateway.State
	}
	if resp.TransitGateway.Tags != nil {
		f5 := []*svcapitypes.Tag{}
		for _, f5iter := range resp.TransitGateway.Tags {
			f5elem := &svcapitypes.Tag{}
			if f5iter.Key != nil {
				f5elem.Key = f5iter.Key
			}
			if f5iter.Value != nil {
				f5elem.Value = f5iter.Value
			}
			f5 = append(f5, f5elem)
		}
		ko.Status.Tags = f5
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.TransitGateway.TransitGatewayArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.TransitGateway.TransitGatewayArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.TransitGateway.TransitGatewayId != nil {
		ko.Status.TransitGatewayID = resp.TransitGateway.TransitGatewayId
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.ModifyTransitGatewayInput, error) {
	res := &svcsdk.ModifyTransitGatewayInput{}

	if r.ko.Spec.Description != nil {
		res.SetDescription(*r.ko.Spec.Description)
	}
	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}
	if r.ko.Spec.Options != nil {
		f2 := &svcsdk.ModifyTransitGatewayOptions{}
		if r.ko.Spec.Options.AddTransitGatewayCIDRBlocks != nil {
			f2f0 := []*string{}
			for _, f2f0iter := range r.ko.Spec.Options.AddTransitGatewayCIDRBlocks {
				var f2f0elem string
				f2f0elem = *f2f0iter
				f2f0 = append(f2f0, &f2f0elem)
			}
			f2.SetAddTransitGatewayCidrBlocks(f2f0)
		}
		if r.ko.Spec.Options.AssociationDefaultRouteTableID != nil {
			f2.SetAssociationDefaultRouteTableId(*r.ko.Spec.Options.AssociationDefaultRouteTableID)
		}
		if r.ko.Spec.Options.AutoAcceptSharedAttachments != nil {
			f2.SetAutoAcceptSharedAttachments(*r.ko.Spec.Options.AutoAcceptSharedAttachments)
		}
		if r.ko.Spec.Options.DefaultRouteTableAssociation != nil {
			f2.SetDefaultRouteTableAssociation(*r.ko.Spec.Options.DefaultRouteTableAssociation)
		}
		if r.ko.Spec.Options.DefaultRouteTablePropagation != nil {
			f2.SetDefaultRouteTablePropagation(*r.ko.Spec.Options.DefaultRouteTablePropagation)
		}
		if r.ko.Spec.Options.DNSSupport != nil {
			f2.SetDnsSupport(*r.ko.Spec.Options.DNSSupport)
		}
		if r.ko.Spec.Options.PropagationDefaultRouteTableID != nil {
			f2.SetPropagationDefaultRouteTableId(*r.ko.Spec.Options.PropagationDefaultRouteTableID)
		}
		if r.ko.Spec.Options.RemoveTransitGatewayCIDRBlocks != nil {
			f2f7 := []*string{}
			for _, f2f7iter := range r.ko.Spec.Options.RemoveTransitGatewayCIDRBlocks {
				var f2f7elem string
				f2f7elem = *f2f7iter
				f2f7 = append(f2f7, &f2f7elem)
			}
			f2.SetRemoveTransitGatewayCidrBlocks(f2f7)
		}
		if r.ko.Spec.Options.VPNEcmpSupport != nil {
			f2.SetVpnEcmpSupport(*r.ko.Spec.Options.VPNEcmpSupport)
		}
		res.SetOptions(f2)
	}
	if r.ko.Status.TransitGatewayID != nil {
		res.SetTransitGatewayId(*r.ko.Status.TransitGatewayID)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) error {

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return err
	}
	_, respErr := rm.sdkapi.DeleteTransitGatewayWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteTransitGateway", respErr)
	return respErr
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteTransitGatewayInput, error) {
	res := &svcsdk.DeleteTransitGatewayInput{}

	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}
	if r.ko.Status.TransitGatewayID != nil {
		res.SetTransitGatewayId(*r.ko.Status.TransitGatewayID)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.TransitGateway,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
			break
		}
	}

	if rm.terminalAWSError(err) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		terminalCondition.Status = corev1.ConditionTrue
		awsErr, _ := ackerr.AWSError(err)
		errorMessage := awsErr.Message()
		terminalCondition.Message = &errorMessage
	} else if terminalCondition != nil {
		terminalCondition.Status = corev1.ConditionFalse
		terminalCondition.Message = nil
	}
	if terminalCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
