// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package vpc_endpoint_connection_notification

import (
	"context"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/ec2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/ec2-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.EC2{}
	_ = &svcapitypes.VPCEndpointConnectionNotification{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.DescribeVpcEndpointConnectionNotificationsWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeVpcEndpointConnectionNotifications", respErr)
	if respErr != nil {
		if awsErr, ok := ackerr.AWSError(respErr); ok && awsErr.Code() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, respErr
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.ConnectionNotificationSet {
		if elem.ConnectionEvents != nil {
			f0 := []*string{}
			for _, f0iter := range elem.ConnectionEvents {
				var f0elem string
				f0elem = *f0iter
				f0 = append(f0, &f0elem)
			}
			ko.Spec.ConnectionEvents = f0
		}
		if elem.ConnectionNotificationArn != nil {
			ko.Spec.ConnectionNotificationARN = elem.ConnectionNotificationArn
		}
		if elem.ServiceId != nil {
			ko.Spec.ServiceID = elem.ServiceId
		}
		if elem.VpcEndpointId != nil {
			ko.Spec.VPCEndpointID = elem.VpcEndpointId
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeVpcEndpointConnectionNotificationsInput, error) {
	res := &svcsdk.DescribeVpcEndpointConnectionNotificationsInput{}

	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a new resource with any fields in the Status field filled in
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newCreateRequestPayload(ctx, r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.CreateVpcEndpointConnectionNotificationWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateVpcEndpointConnectionNotification", respErr)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.ConnectionNotification != nil {
		f1 := &svcapitypes.ConnectionNotification{}
		if resp.ConnectionNotification.ConnectionEvents != nil {
			f1f0 := []*string{}
			for _, f1f0iter := range resp.ConnectionNotification.ConnectionEvents {
				var f1f0elem string
				f1f0elem = *f1f0iter
				f1f0 = append(f1f0, &f1f0elem)
			}
			f1.ConnectionEvents = f1f0
		}
		if resp.ConnectionNotification.ConnectionNotificationArn != nil {
			f1.ConnectionNotificationARN = resp.ConnectionNotification.ConnectionNotificationArn
		}
		if resp.ConnectionNotification.ConnectionNotificationId != nil {
			f1.ConnectionNotificationID = resp.ConnectionNotification.ConnectionNotificationId
		}
		if resp.ConnectionNotification.ConnectionNotificationState != nil {
			f1.ConnectionNotificationState = resp.ConnectionNotification.ConnectionNotificationState
		}
		if resp.ConnectionNotification.ConnectionNotificationType != nil {
			f1.ConnectionNotificationType = resp.ConnectionNotification.ConnectionNotificationType
		}
		if resp.ConnectionNotification.ServiceId != nil {
			f1.ServiceID = resp.ConnectionNotification.ServiceId
		}
		if resp.ConnectionNotification.VpcEndpointId != nil {
			f1.VPCEndpointID = resp.ConnectionNotification.VpcEndpointId
		}
		ko.Status.ConnectionNotification = f1
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateVpcEndpointConnectionNotificationInput, error) {
	res := &svcsdk.CreateVpcEndpointConnectionNotificationInput{}

	if r.ko.Spec.ClientToken != nil {
		res.SetClientToken(*r.ko.Spec.ClientToken)
	}
	if r.ko.Spec.ConnectionEvents != nil {
		f1 := []*string{}
		for _, f1iter := range r.ko.Spec.ConnectionEvents {
			var f1elem string
			f1elem = *f1iter
			f1 = append(f1, &f1elem)
		}
		res.SetConnectionEvents(f1)
	}
	if r.ko.Spec.ConnectionNotificationARN != nil {
		res.SetConnectionNotificationArn(*r.ko.Spec.ConnectionNotificationARN)
	}
	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}
	if r.ko.Spec.ServiceID != nil {
		res.SetServiceId(*r.ko.Spec.ServiceID)
	}
	if r.ko.Spec.VPCEndpointID != nil {
		res.SetVpcEndpointId(*r.ko.Spec.VPCEndpointID)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	diffReporter *ackcompare.Reporter,
) (*resource, error) {

	input, err := rm.newUpdateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	_, respErr := rm.sdkapi.ModifyVpcEndpointConnectionNotificationWithContext(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyVpcEndpointConnectionNotification", respErr)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.ModifyVpcEndpointConnectionNotificationInput, error) {
	res := &svcsdk.ModifyVpcEndpointConnectionNotificationInput{}

	if r.ko.Spec.ConnectionEvents != nil {
		f0 := []*string{}
		for _, f0iter := range r.ko.Spec.ConnectionEvents {
			var f0elem string
			f0elem = *f0iter
			f0 = append(f0, &f0elem)
		}
		res.SetConnectionEvents(f0)
	}
	if r.ko.Spec.ConnectionNotificationARN != nil {
		res.SetConnectionNotificationArn(*r.ko.Spec.ConnectionNotificationARN)
	}
	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) error {
	// TODO(jaypipes): Figure this out...
	return nil

}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.VPCEndpointConnectionNotification,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
			break
		}
	}

	if rm.terminalAWSError(err) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		terminalCondition.Status = corev1.ConditionTrue
		awsErr, _ := ackerr.AWSError(err)
		errorMessage := awsErr.Message()
		terminalCondition.Message = &errorMessage
	} else if terminalCondition != nil {
		terminalCondition.Status = corev1.ConditionFalse
		terminalCondition.Message = nil
	}
	if terminalCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
