// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package traffic_mirror_target

import (
	"context"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/ec2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/ec2-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.EC2{}
	_ = &svcapitypes.TrafficMirrorTarget{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.DescribeTrafficMirrorTargetsWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeTrafficMirrorTargets", respErr)
	if respErr != nil {
		if awsErr, ok := ackerr.AWSError(respErr); ok && awsErr.Code() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, respErr
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.TrafficMirrorTargets {
		if elem.Description != nil {
			ko.Spec.Description = elem.Description
		}
		if elem.NetworkInterfaceId != nil {
			ko.Spec.NetworkInterfaceID = elem.NetworkInterfaceId
		}
		if elem.NetworkLoadBalancerArn != nil {
			ko.Spec.NetworkLoadBalancerARN = elem.NetworkLoadBalancerArn
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeTrafficMirrorTargetsInput, error) {
	res := &svcsdk.DescribeTrafficMirrorTargetsInput{}

	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a new resource with any fields in the Status field filled in
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newCreateRequestPayload(ctx, r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.CreateTrafficMirrorTargetWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateTrafficMirrorTarget", respErr)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.TrafficMirrorTarget != nil {
		f1 := &svcapitypes.TrafficMirrorTarget_SDK{}
		if resp.TrafficMirrorTarget.Description != nil {
			f1.Description = resp.TrafficMirrorTarget.Description
		}
		if resp.TrafficMirrorTarget.NetworkInterfaceId != nil {
			f1.NetworkInterfaceID = resp.TrafficMirrorTarget.NetworkInterfaceId
		}
		if resp.TrafficMirrorTarget.NetworkLoadBalancerArn != nil {
			f1.NetworkLoadBalancerARN = resp.TrafficMirrorTarget.NetworkLoadBalancerArn
		}
		if resp.TrafficMirrorTarget.OwnerId != nil {
			f1.OwnerID = resp.TrafficMirrorTarget.OwnerId
		}
		if resp.TrafficMirrorTarget.Tags != nil {
			f1f4 := []*svcapitypes.Tag{}
			for _, f1f4iter := range resp.TrafficMirrorTarget.Tags {
				f1f4elem := &svcapitypes.Tag{}
				if f1f4iter.Key != nil {
					f1f4elem.Key = f1f4iter.Key
				}
				if f1f4iter.Value != nil {
					f1f4elem.Value = f1f4iter.Value
				}
				f1f4 = append(f1f4, f1f4elem)
			}
			f1.Tags = f1f4
		}
		if resp.TrafficMirrorTarget.TrafficMirrorTargetId != nil {
			f1.TrafficMirrorTargetID = resp.TrafficMirrorTarget.TrafficMirrorTargetId
		}
		if resp.TrafficMirrorTarget.Type != nil {
			f1.Type = resp.TrafficMirrorTarget.Type
		}
		ko.Status.TrafficMirrorTarget = f1
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateTrafficMirrorTargetInput, error) {
	res := &svcsdk.CreateTrafficMirrorTargetInput{}

	if r.ko.Spec.ClientToken != nil {
		res.SetClientToken(*r.ko.Spec.ClientToken)
	}
	if r.ko.Spec.Description != nil {
		res.SetDescription(*r.ko.Spec.Description)
	}
	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}
	if r.ko.Spec.NetworkInterfaceID != nil {
		res.SetNetworkInterfaceId(*r.ko.Spec.NetworkInterfaceID)
	}
	if r.ko.Spec.NetworkLoadBalancerARN != nil {
		res.SetNetworkLoadBalancerArn(*r.ko.Spec.NetworkLoadBalancerARN)
	}
	if r.ko.Spec.TagSpecifications != nil {
		f5 := []*svcsdk.TagSpecification{}
		for _, f5iter := range r.ko.Spec.TagSpecifications {
			f5elem := &svcsdk.TagSpecification{}
			if f5iter.ResourceType != nil {
				f5elem.SetResourceType(*f5iter.ResourceType)
			}
			if f5iter.Tags != nil {
				f5elemf1 := []*svcsdk.Tag{}
				for _, f5elemf1iter := range f5iter.Tags {
					f5elemf1elem := &svcsdk.Tag{}
					if f5elemf1iter.Key != nil {
						f5elemf1elem.SetKey(*f5elemf1iter.Key)
					}
					if f5elemf1iter.Value != nil {
						f5elemf1elem.SetValue(*f5elemf1iter.Value)
					}
					f5elemf1 = append(f5elemf1, f5elemf1elem)
				}
				f5elem.SetTags(f5elemf1)
			}
			f5 = append(f5, f5elem)
		}
		res.SetTagSpecifications(f5)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	diffReporter *ackcompare.Reporter,
) (*resource, error) {
	// TODO(jaypipes): Figure this out...
	return nil, ackerr.NotImplemented
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) error {

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return err
	}
	_, respErr := rm.sdkapi.DeleteTrafficMirrorTargetWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteTrafficMirrorTarget", respErr)
	return respErr
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteTrafficMirrorTargetInput, error) {
	res := &svcsdk.DeleteTrafficMirrorTargetInput{}

	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.TrafficMirrorTarget,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
			break
		}
	}

	if rm.terminalAWSError(err) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		terminalCondition.Status = corev1.ConditionTrue
		awsErr, _ := ackerr.AWSError(err)
		errorMessage := awsErr.Message()
		terminalCondition.Message = &errorMessage
	} else if terminalCondition != nil {
		terminalCondition.Status = corev1.ConditionFalse
		terminalCondition.Message = nil
	}
	if terminalCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
