apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/ec2.services.k8s.aws_capacityreservations.yaml
  - bases/ec2.services.k8s.aws_carriergateways.yaml
  - bases/ec2.services.k8s.aws_clientvpnendpoints.yaml
  - bases/ec2.services.k8s.aws_clientvpnroutes.yaml
  - bases/ec2.services.k8s.aws_customergateways.yaml
  - bases/ec2.services.k8s.aws_defaultsubnets.yaml
  - bases/ec2.services.k8s.aws_defaultvpcs.yaml
  - bases/ec2.services.k8s.aws_egressonlyinternetgateways.yaml
  - bases/ec2.services.k8s.aws_fpgaimages.yaml
  - bases/ec2.services.k8s.aws_fleets.yaml
  - bases/ec2.services.k8s.aws_images.yaml
  - bases/ec2.services.k8s.aws_instanceexporttasks.yaml
  - bases/ec2.services.k8s.aws_internetgateways.yaml
  - bases/ec2.services.k8s.aws_keypairs.yaml
  - bases/ec2.services.k8s.aws_launchtemplates.yaml
  - bases/ec2.services.k8s.aws_launchtemplateversions.yaml
  - bases/ec2.services.k8s.aws_localgatewayroutes.yaml
  - bases/ec2.services.k8s.aws_localgatewayroutetablevpcassociations.yaml
  - bases/ec2.services.k8s.aws_managedprefixlists.yaml
  - bases/ec2.services.k8s.aws_natgateways.yaml
  - bases/ec2.services.k8s.aws_networkacls.yaml
  - bases/ec2.services.k8s.aws_networkaclentries.yaml
  - bases/ec2.services.k8s.aws_networkinsightspaths.yaml
  - bases/ec2.services.k8s.aws_networkinterfaces.yaml
  - bases/ec2.services.k8s.aws_networkinterfacepermissions.yaml
  - bases/ec2.services.k8s.aws_placementgroups.yaml
  - bases/ec2.services.k8s.aws_reservedinstanceslistings.yaml
  - bases/ec2.services.k8s.aws_routes.yaml
  - bases/ec2.services.k8s.aws_routetables.yaml
  - bases/ec2.services.k8s.aws_securitygroups.yaml
  - bases/ec2.services.k8s.aws_snapshots.yaml
  - bases/ec2.services.k8s.aws_spotdatafeedsubscriptions.yaml
  - bases/ec2.services.k8s.aws_subnets.yaml
  - bases/ec2.services.k8s.aws_trafficmirrorfilters.yaml
  - bases/ec2.services.k8s.aws_trafficmirrorfilterrules.yaml
  - bases/ec2.services.k8s.aws_trafficmirrorsessions.yaml
  - bases/ec2.services.k8s.aws_trafficmirrortargets.yaml
  - bases/ec2.services.k8s.aws_transitgateways.yaml
  - bases/ec2.services.k8s.aws_transitgatewayconnects.yaml
  - bases/ec2.services.k8s.aws_transitgatewayconnectpeers.yaml
  - bases/ec2.services.k8s.aws_transitgatewaymulticastdomains.yaml
  - bases/ec2.services.k8s.aws_transitgatewaypeeringattachments.yaml
  - bases/ec2.services.k8s.aws_transitgatewayprefixlistreferences.yaml
  - bases/ec2.services.k8s.aws_transitgatewayroutes.yaml
  - bases/ec2.services.k8s.aws_transitgatewayroutetables.yaml
  - bases/ec2.services.k8s.aws_transitgatewayvpcattachments.yaml
  - bases/ec2.services.k8s.aws_vpcs.yaml
  - bases/ec2.services.k8s.aws_vpcendpoints.yaml
  - bases/ec2.services.k8s.aws_vpcendpointconnectionnotifications.yaml
  - bases/ec2.services.k8s.aws_vpcendpointserviceconfigurations.yaml
  - bases/ec2.services.k8s.aws_vpcpeeringconnections.yaml
  - bases/ec2.services.k8s.aws_vpnconnections.yaml
  - bases/ec2.services.k8s.aws_vpnconnectionroutes.yaml
  - bases/ec2.services.k8s.aws_vpngateways.yaml
  - bases/ec2.services.k8s.aws_volumes.yaml
