// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CustomerGatewaySpec defines the desired state of CustomerGateway
type CustomerGatewaySpec struct {
	// +kubebuilder:validation:Required
	BGPASN            *int64              `json:"bgpASN"`
	CertificateARN    *string             `json:"certificateARN,omitempty"`
	DeviceName        *string             `json:"deviceName,omitempty"`
	DryRun            *bool               `json:"dryRun,omitempty"`
	PublicIP          *string             `json:"publicIP,omitempty"`
	TagSpecifications []*TagSpecification `json:"tagSpecifications,omitempty"`
	// +kubebuilder:validation:Required
	Type *string `json:"type_"`
}

// CustomerGatewayStatus defines the observed state of CustomerGateway
type CustomerGatewayStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	Conditions        []*ackv1alpha1.Condition `json:"conditions"`
	CustomerGatewayID *string                  `json:"customerGatewayID,omitempty"`
	IPAddress         *string                  `json:"ipAddress,omitempty"`
	State             *string                  `json:"state,omitempty"`
	Tags              []*Tag                   `json:"tags,omitempty"`
}

// CustomerGateway is the Schema for the CustomerGateways API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type CustomerGateway struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CustomerGatewaySpec   `json:"spec,omitempty"`
	Status            CustomerGatewayStatus `json:"status,omitempty"`
}

// CustomerGatewayList contains a list of CustomerGateway
// +kubebuilder:object:root=true
type CustomerGatewayList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomerGateway `json:"items"`
}

func init() {
	SchemeBuilder.Register(&CustomerGateway{}, &CustomerGatewayList{})
}
