// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// InstanceExportTaskSpec defines the desired state of InstanceExportTask
type InstanceExportTaskSpec struct {
	Description    *string                      `json:"description,omitempty"`
	ExportToS3Task *ExportToS3TaskSpecification `json:"exportToS3Task,omitempty"`
	// +kubebuilder:validation:Required
	InstanceID        *string             `json:"instanceID"`
	TagSpecifications []*TagSpecification `json:"tagSpecifications,omitempty"`
	TargetEnvironment *string             `json:"targetEnvironment,omitempty"`
}

// InstanceExportTaskStatus defines the observed state of InstanceExportTask
type InstanceExportTaskStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	Conditions            []*ackv1alpha1.Condition `json:"conditions"`
	ExportTaskID          *string                  `json:"exportTaskID,omitempty"`
	InstanceExportDetails *InstanceExportDetails   `json:"instanceExportDetails,omitempty"`
	State                 *string                  `json:"state,omitempty"`
	StatusMessage         *string                  `json:"statusMessage,omitempty"`
	Tags                  []*Tag                   `json:"tags,omitempty"`
}

// InstanceExportTask is the Schema for the InstanceExportTasks API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type InstanceExportTask struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              InstanceExportTaskSpec   `json:"spec,omitempty"`
	Status            InstanceExportTaskStatus `json:"status,omitempty"`
}

// InstanceExportTaskList contains a list of InstanceExportTask
// +kubebuilder:object:root=true
type InstanceExportTaskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InstanceExportTask `json:"items"`
}

func init() {
	SchemeBuilder.Register(&InstanceExportTask{}, &InstanceExportTaskList{})
}
