// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// KeyPairSpec defines the desired state of KeyPair
type KeyPairSpec struct {
	DryRun *bool `json:"dryRun,omitempty"`
	// +kubebuilder:validation:Required
	KeyName           *string             `json:"keyName"`
	TagSpecifications []*TagSpecification `json:"tagSpecifications,omitempty"`
}

// KeyPairStatus defines the observed state of KeyPair
type KeyPairStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	Conditions     []*ackv1alpha1.Condition `json:"conditions"`
	KeyFingerprint *string                  `json:"keyFingerprint,omitempty"`
	KeyMaterial    *string                  `json:"keyMaterial,omitempty"`
	KeyPairID      *string                  `json:"keyPairID,omitempty"`
	Tags           []*Tag                   `json:"tags,omitempty"`
}

// KeyPair is the Schema for the KeyPairs API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type KeyPair struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              KeyPairSpec   `json:"spec,omitempty"`
	Status            KeyPairStatus `json:"status,omitempty"`
}

// KeyPairList contains a list of KeyPair
// +kubebuilder:object:root=true
type KeyPairList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KeyPair `json:"items"`
}

func init() {
	SchemeBuilder.Register(&KeyPair{}, &KeyPairList{})
}
