// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ManagedPrefixListSpec defines the desired state of ManagedPrefixList
type ManagedPrefixListSpec struct {
	// +kubebuilder:validation:Required
	AddressFamily *string               `json:"addressFamily"`
	ClientToken   *string               `json:"clientToken,omitempty"`
	DryRun        *bool                 `json:"dryRun,omitempty"`
	Entries       []*AddPrefixListEntry `json:"entries,omitempty"`
	// +kubebuilder:validation:Required
	MaxEntries *int64 `json:"maxEntries"`
	// +kubebuilder:validation:Required
	PrefixListName    *string             `json:"prefixListName"`
	TagSpecifications []*TagSpecification `json:"tagSpecifications,omitempty"`
}

// ManagedPrefixListStatus defines the observed state of ManagedPrefixList
type ManagedPrefixListStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	Conditions    []*ackv1alpha1.Condition `json:"conditions"`
	OwnerID       *string                  `json:"ownerID,omitempty"`
	PrefixListARN *string                  `json:"prefixListARN,omitempty"`
	PrefixListID  *string                  `json:"prefixListID,omitempty"`
	State         *string                  `json:"state,omitempty"`
	StateMessage  *string                  `json:"stateMessage,omitempty"`
	Tags          []*Tag                   `json:"tags,omitempty"`
	Version       *int64                   `json:"version,omitempty"`
}

// ManagedPrefixList is the Schema for the ManagedPrefixLists API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ManagedPrefixList struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ManagedPrefixListSpec   `json:"spec,omitempty"`
	Status            ManagedPrefixListStatus `json:"status,omitempty"`
}

// ManagedPrefixListList contains a list of ManagedPrefixList
// +kubebuilder:object:root=true
type ManagedPrefixListList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ManagedPrefixList `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ManagedPrefixList{}, &ManagedPrefixListList{})
}
