// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NetworkInsightsPathSpec defines the desired state of NetworkInsightsPath
type NetworkInsightsPathSpec struct {
	// +kubebuilder:validation:Required
	ClientToken *string `json:"clientToken"`
	// +kubebuilder:validation:Required
	Destination     *string `json:"destination"`
	DestinationIP   *string `json:"destinationIP,omitempty"`
	DestinationPort *int64  `json:"destinationPort,omitempty"`
	DryRun          *bool   `json:"dryRun,omitempty"`
	// +kubebuilder:validation:Required
	Protocol *string `json:"protocol"`
	// +kubebuilder:validation:Required
	Source            *string             `json:"source"`
	SourceIP          *string             `json:"sourceIP,omitempty"`
	TagSpecifications []*TagSpecification `json:"tagSpecifications,omitempty"`
}

// NetworkInsightsPathStatus defines the observed state of NetworkInsightsPath
type NetworkInsightsPathStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	Conditions            []*ackv1alpha1.Condition `json:"conditions"`
	CreatedDate           *metav1.Time             `json:"createdDate,omitempty"`
	NetworkInsightsPathID *string                  `json:"networkInsightsPathID,omitempty"`
	Tags                  []*Tag                   `json:"tags,omitempty"`
}

// NetworkInsightsPath is the Schema for the NetworkInsightsPaths API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type NetworkInsightsPath struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkInsightsPathSpec   `json:"spec,omitempty"`
	Status            NetworkInsightsPathStatus `json:"status,omitempty"`
}

// NetworkInsightsPathList contains a list of NetworkInsightsPath
// +kubebuilder:object:root=true
type NetworkInsightsPathList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkInsightsPath `json:"items"`
}

func init() {
	SchemeBuilder.Register(&NetworkInsightsPath{}, &NetworkInsightsPathList{})
}
