// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VPCEndpointConnectionNotificationSpec defines the desired state of VPCEndpointConnectionNotification
type VPCEndpointConnectionNotificationSpec struct {
	ClientToken *string `json:"clientToken,omitempty"`
	// +kubebuilder:validation:Required
	ConnectionEvents []*string `json:"connectionEvents"`
	// +kubebuilder:validation:Required
	ConnectionNotificationARN *string `json:"connectionNotificationARN"`
	DryRun                    *bool   `json:"dryRun,omitempty"`
	ServiceID                 *string `json:"serviceID,omitempty"`
	VPCEndpointID             *string `json:"vpcEndpointID,omitempty"`
}

// VPCEndpointConnectionNotificationStatus defines the observed state of VPCEndpointConnectionNotification
type VPCEndpointConnectionNotificationStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	Conditions             []*ackv1alpha1.Condition `json:"conditions"`
	ConnectionNotification *ConnectionNotification  `json:"connectionNotification,omitempty"`
}

// VPCEndpointConnectionNotification is the Schema for the VPCEndpointConnectionNotifications API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type VPCEndpointConnectionNotification struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VPCEndpointConnectionNotificationSpec   `json:"spec,omitempty"`
	Status            VPCEndpointConnectionNotificationStatus `json:"status,omitempty"`
}

// VPCEndpointConnectionNotificationList contains a list of VPCEndpointConnectionNotification
// +kubebuilder:object:root=true
type VPCEndpointConnectionNotificationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VPCEndpointConnectionNotification `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VPCEndpointConnectionNotification{}, &VPCEndpointConnectionNotificationList{})
}
