// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package launch_template_version

import (
	"context"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/ec2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/ec2-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.EC2{}
	_ = &svcapitypes.LaunchTemplateVersion{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.DescribeLaunchTemplateVersionsWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeLaunchTemplateVersions", respErr)
	if respErr != nil {
		if awsErr, ok := ackerr.AWSError(respErr); ok && awsErr.Code() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, respErr
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.LaunchTemplateVersions {
		if elem.LaunchTemplateData != nil {
			f3 := &svcapitypes.RequestLaunchTemplateData{}
			if elem.LaunchTemplateData.BlockDeviceMappings != nil {
				f3f0 := []*svcapitypes.LaunchTemplateBlockDeviceMappingRequest{}
				for _, f3f0iter := range elem.LaunchTemplateData.BlockDeviceMappings {
					f3f0elem := &svcapitypes.LaunchTemplateBlockDeviceMappingRequest{}
					if f3f0iter.DeviceName != nil {
						f3f0elem.DeviceName = f3f0iter.DeviceName
					}
					if f3f0iter.Ebs != nil {
						f3f0elemf1 := &svcapitypes.LaunchTemplateEBSBlockDeviceRequest{}
						if f3f0iter.Ebs.DeleteOnTermination != nil {
							f3f0elemf1.DeleteOnTermination = f3f0iter.Ebs.DeleteOnTermination
						}
						if f3f0iter.Ebs.Encrypted != nil {
							f3f0elemf1.Encrypted = f3f0iter.Ebs.Encrypted
						}
						if f3f0iter.Ebs.Iops != nil {
							f3f0elemf1.IOPS = f3f0iter.Ebs.Iops
						}
						if f3f0iter.Ebs.KmsKeyId != nil {
							f3f0elemf1.KMSKeyID = f3f0iter.Ebs.KmsKeyId
						}
						if f3f0iter.Ebs.SnapshotId != nil {
							f3f0elemf1.SnapshotID = f3f0iter.Ebs.SnapshotId
						}
						if f3f0iter.Ebs.Throughput != nil {
							f3f0elemf1.Throughput = f3f0iter.Ebs.Throughput
						}
						if f3f0iter.Ebs.VolumeSize != nil {
							f3f0elemf1.VolumeSize = f3f0iter.Ebs.VolumeSize
						}
						if f3f0iter.Ebs.VolumeType != nil {
							f3f0elemf1.VolumeType = f3f0iter.Ebs.VolumeType
						}
						f3f0elem.EBS = f3f0elemf1
					}
					if f3f0iter.NoDevice != nil {
						f3f0elem.NoDevice = f3f0iter.NoDevice
					}
					if f3f0iter.VirtualName != nil {
						f3f0elem.VirtualName = f3f0iter.VirtualName
					}
					f3f0 = append(f3f0, f3f0elem)
				}
				f3.BlockDeviceMappings = f3f0
			}
			if elem.LaunchTemplateData.CapacityReservationSpecification != nil {
				f3f1 := &svcapitypes.LaunchTemplateCapacityReservationSpecificationRequest{}
				if elem.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationPreference != nil {
					f3f1.CapacityReservationPreference = elem.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationPreference
				}
				if elem.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget != nil {
					f3f1f1 := &svcapitypes.CapacityReservationTarget{}
					if elem.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationId != nil {
						f3f1f1.CapacityReservationID = elem.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationId
					}
					if elem.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupArn != nil {
						f3f1f1.CapacityReservationResourceGroupARN = elem.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupArn
					}
					f3f1.CapacityReservationTarget = f3f1f1
				}
				f3.CapacityReservationSpecification = f3f1
			}
			if elem.LaunchTemplateData.CpuOptions != nil {
				f3f2 := &svcapitypes.LaunchTemplateCPUOptionsRequest{}
				if elem.LaunchTemplateData.CpuOptions.CoreCount != nil {
					f3f2.CoreCount = elem.LaunchTemplateData.CpuOptions.CoreCount
				}
				if elem.LaunchTemplateData.CpuOptions.ThreadsPerCore != nil {
					f3f2.ThreadsPerCore = elem.LaunchTemplateData.CpuOptions.ThreadsPerCore
				}
				f3.CPUOptions = f3f2
			}
			if elem.LaunchTemplateData.CreditSpecification != nil {
				f3f3 := &svcapitypes.CreditSpecificationRequest{}
				if elem.LaunchTemplateData.CreditSpecification.CpuCredits != nil {
					f3f3.CPUCredits = elem.LaunchTemplateData.CreditSpecification.CpuCredits
				}
				f3.CreditSpecification = f3f3
			}
			if elem.LaunchTemplateData.DisableApiTermination != nil {
				f3.DisableAPITermination = elem.LaunchTemplateData.DisableApiTermination
			}
			if elem.LaunchTemplateData.EbsOptimized != nil {
				f3.EBSOptimized = elem.LaunchTemplateData.EbsOptimized
			}
			if elem.LaunchTemplateData.ElasticGpuSpecifications != nil {
				f3f6 := []*svcapitypes.ElasticGPUSpecification{}
				for _, f3f6iter := range elem.LaunchTemplateData.ElasticGpuSpecifications {
					f3f6elem := &svcapitypes.ElasticGPUSpecification{}
					if f3f6iter.Type != nil {
						f3f6elem.Type = f3f6iter.Type
					}
					f3f6 = append(f3f6, f3f6elem)
				}
				f3.ElasticGPUSpecifications = f3f6
			}
			if elem.LaunchTemplateData.ElasticInferenceAccelerators != nil {
				f3f7 := []*svcapitypes.LaunchTemplateElasticInferenceAccelerator{}
				for _, f3f7iter := range elem.LaunchTemplateData.ElasticInferenceAccelerators {
					f3f7elem := &svcapitypes.LaunchTemplateElasticInferenceAccelerator{}
					if f3f7iter.Count != nil {
						f3f7elem.Count = f3f7iter.Count
					}
					if f3f7iter.Type != nil {
						f3f7elem.Type = f3f7iter.Type
					}
					f3f7 = append(f3f7, f3f7elem)
				}
				f3.ElasticInferenceAccelerators = f3f7
			}
			if elem.LaunchTemplateData.EnclaveOptions != nil {
				f3f8 := &svcapitypes.LaunchTemplateEnclaveOptionsRequest{}
				if elem.LaunchTemplateData.EnclaveOptions.Enabled != nil {
					f3f8.Enabled = elem.LaunchTemplateData.EnclaveOptions.Enabled
				}
				f3.EnclaveOptions = f3f8
			}
			if elem.LaunchTemplateData.HibernationOptions != nil {
				f3f9 := &svcapitypes.LaunchTemplateHibernationOptionsRequest{}
				if elem.LaunchTemplateData.HibernationOptions.Configured != nil {
					f3f9.Configured = elem.LaunchTemplateData.HibernationOptions.Configured
				}
				f3.HibernationOptions = f3f9
			}
			if elem.LaunchTemplateData.IamInstanceProfile != nil {
				f3f10 := &svcapitypes.LaunchTemplateIAMInstanceProfileSpecificationRequest{}
				if elem.LaunchTemplateData.IamInstanceProfile.Arn != nil {
					f3f10.ARN = elem.LaunchTemplateData.IamInstanceProfile.Arn
				}
				if elem.LaunchTemplateData.IamInstanceProfile.Name != nil {
					f3f10.Name = elem.LaunchTemplateData.IamInstanceProfile.Name
				}
				f3.IAMInstanceProfile = f3f10
			}
			if elem.LaunchTemplateData.ImageId != nil {
				f3.ImageID = elem.LaunchTemplateData.ImageId
			}
			if elem.LaunchTemplateData.InstanceInitiatedShutdownBehavior != nil {
				f3.InstanceInitiatedShutdownBehavior = elem.LaunchTemplateData.InstanceInitiatedShutdownBehavior
			}
			if elem.LaunchTemplateData.InstanceMarketOptions != nil {
				f3f13 := &svcapitypes.LaunchTemplateInstanceMarketOptionsRequest{}
				if elem.LaunchTemplateData.InstanceMarketOptions.MarketType != nil {
					f3f13.MarketType = elem.LaunchTemplateData.InstanceMarketOptions.MarketType
				}
				if elem.LaunchTemplateData.InstanceMarketOptions.SpotOptions != nil {
					f3f13f1 := &svcapitypes.LaunchTemplateSpotMarketOptionsRequest{}
					if elem.LaunchTemplateData.InstanceMarketOptions.SpotOptions.BlockDurationMinutes != nil {
						f3f13f1.BlockDurationMinutes = elem.LaunchTemplateData.InstanceMarketOptions.SpotOptions.BlockDurationMinutes
					}
					if elem.LaunchTemplateData.InstanceMarketOptions.SpotOptions.InstanceInterruptionBehavior != nil {
						f3f13f1.InstanceInterruptionBehavior = elem.LaunchTemplateData.InstanceMarketOptions.SpotOptions.InstanceInterruptionBehavior
					}
					if elem.LaunchTemplateData.InstanceMarketOptions.SpotOptions.MaxPrice != nil {
						f3f13f1.MaxPrice = elem.LaunchTemplateData.InstanceMarketOptions.SpotOptions.MaxPrice
					}
					if elem.LaunchTemplateData.InstanceMarketOptions.SpotOptions.SpotInstanceType != nil {
						f3f13f1.SpotInstanceType = elem.LaunchTemplateData.InstanceMarketOptions.SpotOptions.SpotInstanceType
					}
					if elem.LaunchTemplateData.InstanceMarketOptions.SpotOptions.ValidUntil != nil {
						f3f13f1.ValidUntil = &metav1.Time{*elem.LaunchTemplateData.InstanceMarketOptions.SpotOptions.ValidUntil}
					}
					f3f13.SpotOptions = f3f13f1
				}
				f3.InstanceMarketOptions = f3f13
			}
			if elem.LaunchTemplateData.InstanceType != nil {
				f3.InstanceType = elem.LaunchTemplateData.InstanceType
			}
			if elem.LaunchTemplateData.KernelId != nil {
				f3.KernelID = elem.LaunchTemplateData.KernelId
			}
			if elem.LaunchTemplateData.KeyName != nil {
				f3.KeyName = elem.LaunchTemplateData.KeyName
			}
			if elem.LaunchTemplateData.LicenseSpecifications != nil {
				f3f17 := []*svcapitypes.LaunchTemplateLicenseConfigurationRequest{}
				for _, f3f17iter := range elem.LaunchTemplateData.LicenseSpecifications {
					f3f17elem := &svcapitypes.LaunchTemplateLicenseConfigurationRequest{}
					if f3f17iter.LicenseConfigurationArn != nil {
						f3f17elem.LicenseConfigurationARN = f3f17iter.LicenseConfigurationArn
					}
					f3f17 = append(f3f17, f3f17elem)
				}
				f3.LicenseSpecifications = f3f17
			}
			if elem.LaunchTemplateData.MetadataOptions != nil {
				f3f18 := &svcapitypes.LaunchTemplateInstanceMetadataOptionsRequest{}
				if elem.LaunchTemplateData.MetadataOptions.HttpEndpoint != nil {
					f3f18.HTTPEndpoint = elem.LaunchTemplateData.MetadataOptions.HttpEndpoint
				}
				if elem.LaunchTemplateData.MetadataOptions.HttpPutResponseHopLimit != nil {
					f3f18.HTTPPutResponseHopLimit = elem.LaunchTemplateData.MetadataOptions.HttpPutResponseHopLimit
				}
				if elem.LaunchTemplateData.MetadataOptions.HttpTokens != nil {
					f3f18.HTTPTokens = elem.LaunchTemplateData.MetadataOptions.HttpTokens
				}
				f3.MetadataOptions = f3f18
			}
			if elem.LaunchTemplateData.Monitoring != nil {
				f3f19 := &svcapitypes.LaunchTemplatesMonitoringRequest{}
				if elem.LaunchTemplateData.Monitoring.Enabled != nil {
					f3f19.Enabled = elem.LaunchTemplateData.Monitoring.Enabled
				}
				f3.Monitoring = f3f19
			}
			if elem.LaunchTemplateData.NetworkInterfaces != nil {
				f3f20 := []*svcapitypes.LaunchTemplateInstanceNetworkInterfaceSpecificationRequest{}
				for _, f3f20iter := range elem.LaunchTemplateData.NetworkInterfaces {
					f3f20elem := &svcapitypes.LaunchTemplateInstanceNetworkInterfaceSpecificationRequest{}
					if f3f20iter.AssociateCarrierIpAddress != nil {
						f3f20elem.AssociateCarrierIPAddress = f3f20iter.AssociateCarrierIpAddress
					}
					if f3f20iter.AssociatePublicIpAddress != nil {
						f3f20elem.AssociatePublicIPAddress = f3f20iter.AssociatePublicIpAddress
					}
					if f3f20iter.DeleteOnTermination != nil {
						f3f20elem.DeleteOnTermination = f3f20iter.DeleteOnTermination
					}
					if f3f20iter.Description != nil {
						f3f20elem.Description = f3f20iter.Description
					}
					if f3f20iter.DeviceIndex != nil {
						f3f20elem.DeviceIndex = f3f20iter.DeviceIndex
					}
					if f3f20iter.Groups != nil {
						f3f20elemf5 := []*string{}
						for _, f3f20elemf5iter := range f3f20iter.Groups {
							var f3f20elemf5elem string
							f3f20elemf5elem = *f3f20elemf5iter
							f3f20elemf5 = append(f3f20elemf5, &f3f20elemf5elem)
						}
						f3f20elem.Groups = f3f20elemf5
					}
					if f3f20iter.InterfaceType != nil {
						f3f20elem.InterfaceType = f3f20iter.InterfaceType
					}
					if f3f20iter.Ipv6AddressCount != nil {
						f3f20elem.IPv6AddressCount = f3f20iter.Ipv6AddressCount
					}
					if f3f20iter.Ipv6Addresses != nil {
						f3f20elemf8 := []*svcapitypes.InstanceIPv6AddressRequest{}
						for _, f3f20elemf8iter := range f3f20iter.Ipv6Addresses {
							f3f20elemf8elem := &svcapitypes.InstanceIPv6AddressRequest{}
							if f3f20elemf8iter.Ipv6Address != nil {
								f3f20elemf8elem.IPv6Address = f3f20elemf8iter.Ipv6Address
							}
							f3f20elemf8 = append(f3f20elemf8, f3f20elemf8elem)
						}
						f3f20elem.IPv6Addresses = f3f20elemf8
					}
					if f3f20iter.NetworkCardIndex != nil {
						f3f20elem.NetworkCardIndex = f3f20iter.NetworkCardIndex
					}
					if f3f20iter.NetworkInterfaceId != nil {
						f3f20elem.NetworkInterfaceID = f3f20iter.NetworkInterfaceId
					}
					if f3f20iter.PrivateIpAddress != nil {
						f3f20elem.PrivateIPAddress = f3f20iter.PrivateIpAddress
					}
					if f3f20iter.PrivateIpAddresses != nil {
						f3f20elemf12 := []*svcapitypes.PrivateIPAddressSpecification{}
						for _, f3f20elemf12iter := range f3f20iter.PrivateIpAddresses {
							f3f20elemf12elem := &svcapitypes.PrivateIPAddressSpecification{}
							if f3f20elemf12iter.Primary != nil {
								f3f20elemf12elem.Primary = f3f20elemf12iter.Primary
							}
							if f3f20elemf12iter.PrivateIpAddress != nil {
								f3f20elemf12elem.PrivateIPAddress = f3f20elemf12iter.PrivateIpAddress
							}
							f3f20elemf12 = append(f3f20elemf12, f3f20elemf12elem)
						}
						f3f20elem.PrivateIPAddresses = f3f20elemf12
					}
					if f3f20iter.SecondaryPrivateIpAddressCount != nil {
						f3f20elem.SecondaryPrivateIPAddressCount = f3f20iter.SecondaryPrivateIpAddressCount
					}
					if f3f20iter.SubnetId != nil {
						f3f20elem.SubnetID = f3f20iter.SubnetId
					}
					f3f20 = append(f3f20, f3f20elem)
				}
				f3.NetworkInterfaces = f3f20
			}
			if elem.LaunchTemplateData.Placement != nil {
				f3f21 := &svcapitypes.LaunchTemplatePlacementRequest{}
				if elem.LaunchTemplateData.Placement.Affinity != nil {
					f3f21.Affinity = elem.LaunchTemplateData.Placement.Affinity
				}
				if elem.LaunchTemplateData.Placement.AvailabilityZone != nil {
					f3f21.AvailabilityZone = elem.LaunchTemplateData.Placement.AvailabilityZone
				}
				if elem.LaunchTemplateData.Placement.GroupName != nil {
					f3f21.GroupName = elem.LaunchTemplateData.Placement.GroupName
				}
				if elem.LaunchTemplateData.Placement.HostId != nil {
					f3f21.HostID = elem.LaunchTemplateData.Placement.HostId
				}
				if elem.LaunchTemplateData.Placement.HostResourceGroupArn != nil {
					f3f21.HostResourceGroupARN = elem.LaunchTemplateData.Placement.HostResourceGroupArn
				}
				if elem.LaunchTemplateData.Placement.PartitionNumber != nil {
					f3f21.PartitionNumber = elem.LaunchTemplateData.Placement.PartitionNumber
				}
				if elem.LaunchTemplateData.Placement.SpreadDomain != nil {
					f3f21.SpreadDomain = elem.LaunchTemplateData.Placement.SpreadDomain
				}
				if elem.LaunchTemplateData.Placement.Tenancy != nil {
					f3f21.Tenancy = elem.LaunchTemplateData.Placement.Tenancy
				}
				f3.Placement = f3f21
			}
			if elem.LaunchTemplateData.RamDiskId != nil {
				f3.RamDiskID = elem.LaunchTemplateData.RamDiskId
			}
			if elem.LaunchTemplateData.SecurityGroupIds != nil {
				f3f23 := []*string{}
				for _, f3f23iter := range elem.LaunchTemplateData.SecurityGroupIds {
					var f3f23elem string
					f3f23elem = *f3f23iter
					f3f23 = append(f3f23, &f3f23elem)
				}
				f3.SecurityGroupIDs = f3f23
			}
			if elem.LaunchTemplateData.SecurityGroups != nil {
				f3f24 := []*string{}
				for _, f3f24iter := range elem.LaunchTemplateData.SecurityGroups {
					var f3f24elem string
					f3f24elem = *f3f24iter
					f3f24 = append(f3f24, &f3f24elem)
				}
				f3.SecurityGroups = f3f24
			}
			if elem.LaunchTemplateData.TagSpecifications != nil {
				f3f25 := []*svcapitypes.LaunchTemplateTagSpecificationRequest{}
				for _, f3f25iter := range elem.LaunchTemplateData.TagSpecifications {
					f3f25elem := &svcapitypes.LaunchTemplateTagSpecificationRequest{}
					if f3f25iter.ResourceType != nil {
						f3f25elem.ResourceType = f3f25iter.ResourceType
					}
					if f3f25iter.Tags != nil {
						f3f25elemf1 := []*svcapitypes.Tag{}
						for _, f3f25elemf1iter := range f3f25iter.Tags {
							f3f25elemf1elem := &svcapitypes.Tag{}
							if f3f25elemf1iter.Key != nil {
								f3f25elemf1elem.Key = f3f25elemf1iter.Key
							}
							if f3f25elemf1iter.Value != nil {
								f3f25elemf1elem.Value = f3f25elemf1iter.Value
							}
							f3f25elemf1 = append(f3f25elemf1, f3f25elemf1elem)
						}
						f3f25elem.Tags = f3f25elemf1
					}
					f3f25 = append(f3f25, f3f25elem)
				}
				f3.TagSpecifications = f3f25
			}
			if elem.LaunchTemplateData.UserData != nil {
				f3.UserData = elem.LaunchTemplateData.UserData
			}
			ko.Spec.LaunchTemplateData = f3
		}
		if elem.LaunchTemplateId != nil {
			ko.Spec.LaunchTemplateID = elem.LaunchTemplateId
		}
		if elem.LaunchTemplateName != nil {
			ko.Spec.LaunchTemplateName = elem.LaunchTemplateName
		}
		if elem.VersionDescription != nil {
			ko.Spec.VersionDescription = elem.VersionDescription
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeLaunchTemplateVersionsInput, error) {
	res := &svcsdk.DescribeLaunchTemplateVersionsInput{}

	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}
	if r.ko.Spec.LaunchTemplateID != nil {
		res.SetLaunchTemplateId(*r.ko.Spec.LaunchTemplateID)
	}
	if r.ko.Spec.LaunchTemplateName != nil {
		res.SetLaunchTemplateName(*r.ko.Spec.LaunchTemplateName)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a new resource with any fields in the Status field filled in
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newCreateRequestPayload(ctx, r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.CreateLaunchTemplateVersionWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateLaunchTemplateVersion", respErr)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.LaunchTemplateVersion != nil {
		f0 := &svcapitypes.LaunchTemplateVersion_SDK{}
		if resp.LaunchTemplateVersion.CreateTime != nil {
			f0.CreateTime = &metav1.Time{*resp.LaunchTemplateVersion.CreateTime}
		}
		if resp.LaunchTemplateVersion.CreatedBy != nil {
			f0.CreatedBy = resp.LaunchTemplateVersion.CreatedBy
		}
		if resp.LaunchTemplateVersion.DefaultVersion != nil {
			f0.DefaultVersion = resp.LaunchTemplateVersion.DefaultVersion
		}
		if resp.LaunchTemplateVersion.LaunchTemplateData != nil {
			f0f3 := &svcapitypes.ResponseLaunchTemplateData{}
			if resp.LaunchTemplateVersion.LaunchTemplateData.BlockDeviceMappings != nil {
				f0f3f0 := []*svcapitypes.LaunchTemplateBlockDeviceMapping{}
				for _, f0f3f0iter := range resp.LaunchTemplateVersion.LaunchTemplateData.BlockDeviceMappings {
					f0f3f0elem := &svcapitypes.LaunchTemplateBlockDeviceMapping{}
					if f0f3f0iter.DeviceName != nil {
						f0f3f0elem.DeviceName = f0f3f0iter.DeviceName
					}
					if f0f3f0iter.Ebs != nil {
						f0f3f0elemf1 := &svcapitypes.LaunchTemplateEBSBlockDevice{}
						if f0f3f0iter.Ebs.DeleteOnTermination != nil {
							f0f3f0elemf1.DeleteOnTermination = f0f3f0iter.Ebs.DeleteOnTermination
						}
						if f0f3f0iter.Ebs.Encrypted != nil {
							f0f3f0elemf1.Encrypted = f0f3f0iter.Ebs.Encrypted
						}
						if f0f3f0iter.Ebs.Iops != nil {
							f0f3f0elemf1.IOPS = f0f3f0iter.Ebs.Iops
						}
						if f0f3f0iter.Ebs.KmsKeyId != nil {
							f0f3f0elemf1.KMSKeyID = f0f3f0iter.Ebs.KmsKeyId
						}
						if f0f3f0iter.Ebs.SnapshotId != nil {
							f0f3f0elemf1.SnapshotID = f0f3f0iter.Ebs.SnapshotId
						}
						if f0f3f0iter.Ebs.Throughput != nil {
							f0f3f0elemf1.Throughput = f0f3f0iter.Ebs.Throughput
						}
						if f0f3f0iter.Ebs.VolumeSize != nil {
							f0f3f0elemf1.VolumeSize = f0f3f0iter.Ebs.VolumeSize
						}
						if f0f3f0iter.Ebs.VolumeType != nil {
							f0f3f0elemf1.VolumeType = f0f3f0iter.Ebs.VolumeType
						}
						f0f3f0elem.EBS = f0f3f0elemf1
					}
					if f0f3f0iter.NoDevice != nil {
						f0f3f0elem.NoDevice = f0f3f0iter.NoDevice
					}
					if f0f3f0iter.VirtualName != nil {
						f0f3f0elem.VirtualName = f0f3f0iter.VirtualName
					}
					f0f3f0 = append(f0f3f0, f0f3f0elem)
				}
				f0f3.BlockDeviceMappings = f0f3f0
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.CapacityReservationSpecification != nil {
				f0f3f1 := &svcapitypes.LaunchTemplateCapacityReservationSpecificationResponse{}
				if resp.LaunchTemplateVersion.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationPreference != nil {
					f0f3f1.CapacityReservationPreference = resp.LaunchTemplateVersion.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationPreference
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget != nil {
					f0f3f1f1 := &svcapitypes.CapacityReservationTargetResponse{}
					if resp.LaunchTemplateVersion.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationId != nil {
						f0f3f1f1.CapacityReservationID = resp.LaunchTemplateVersion.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationId
					}
					if resp.LaunchTemplateVersion.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupArn != nil {
						f0f3f1f1.CapacityReservationResourceGroupARN = resp.LaunchTemplateVersion.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupArn
					}
					f0f3f1.CapacityReservationTarget = f0f3f1f1
				}
				f0f3.CapacityReservationSpecification = f0f3f1
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.CpuOptions != nil {
				f0f3f2 := &svcapitypes.LaunchTemplateCPUOptions{}
				if resp.LaunchTemplateVersion.LaunchTemplateData.CpuOptions.CoreCount != nil {
					f0f3f2.CoreCount = resp.LaunchTemplateVersion.LaunchTemplateData.CpuOptions.CoreCount
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.CpuOptions.ThreadsPerCore != nil {
					f0f3f2.ThreadsPerCore = resp.LaunchTemplateVersion.LaunchTemplateData.CpuOptions.ThreadsPerCore
				}
				f0f3.CPUOptions = f0f3f2
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.CreditSpecification != nil {
				f0f3f3 := &svcapitypes.CreditSpecification{}
				if resp.LaunchTemplateVersion.LaunchTemplateData.CreditSpecification.CpuCredits != nil {
					f0f3f3.CPUCredits = resp.LaunchTemplateVersion.LaunchTemplateData.CreditSpecification.CpuCredits
				}
				f0f3.CreditSpecification = f0f3f3
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.DisableApiTermination != nil {
				f0f3.DisableAPITermination = resp.LaunchTemplateVersion.LaunchTemplateData.DisableApiTermination
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.EbsOptimized != nil {
				f0f3.EBSOptimized = resp.LaunchTemplateVersion.LaunchTemplateData.EbsOptimized
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.ElasticGpuSpecifications != nil {
				f0f3f6 := []*svcapitypes.ElasticGPUSpecificationResponse{}
				for _, f0f3f6iter := range resp.LaunchTemplateVersion.LaunchTemplateData.ElasticGpuSpecifications {
					f0f3f6elem := &svcapitypes.ElasticGPUSpecificationResponse{}
					if f0f3f6iter.Type != nil {
						f0f3f6elem.Type = f0f3f6iter.Type
					}
					f0f3f6 = append(f0f3f6, f0f3f6elem)
				}
				f0f3.ElasticGPUSpecifications = f0f3f6
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.ElasticInferenceAccelerators != nil {
				f0f3f7 := []*svcapitypes.LaunchTemplateElasticInferenceAcceleratorResponse{}
				for _, f0f3f7iter := range resp.LaunchTemplateVersion.LaunchTemplateData.ElasticInferenceAccelerators {
					f0f3f7elem := &svcapitypes.LaunchTemplateElasticInferenceAcceleratorResponse{}
					if f0f3f7iter.Count != nil {
						f0f3f7elem.Count = f0f3f7iter.Count
					}
					if f0f3f7iter.Type != nil {
						f0f3f7elem.Type = f0f3f7iter.Type
					}
					f0f3f7 = append(f0f3f7, f0f3f7elem)
				}
				f0f3.ElasticInferenceAccelerators = f0f3f7
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.EnclaveOptions != nil {
				f0f3f8 := &svcapitypes.LaunchTemplateEnclaveOptions{}
				if resp.LaunchTemplateVersion.LaunchTemplateData.EnclaveOptions.Enabled != nil {
					f0f3f8.Enabled = resp.LaunchTemplateVersion.LaunchTemplateData.EnclaveOptions.Enabled
				}
				f0f3.EnclaveOptions = f0f3f8
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.HibernationOptions != nil {
				f0f3f9 := &svcapitypes.LaunchTemplateHibernationOptions{}
				if resp.LaunchTemplateVersion.LaunchTemplateData.HibernationOptions.Configured != nil {
					f0f3f9.Configured = resp.LaunchTemplateVersion.LaunchTemplateData.HibernationOptions.Configured
				}
				f0f3.HibernationOptions = f0f3f9
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.IamInstanceProfile != nil {
				f0f3f10 := &svcapitypes.LaunchTemplateIAMInstanceProfileSpecification{}
				if resp.LaunchTemplateVersion.LaunchTemplateData.IamInstanceProfile.Arn != nil {
					f0f3f10.ARN = resp.LaunchTemplateVersion.LaunchTemplateData.IamInstanceProfile.Arn
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.IamInstanceProfile.Name != nil {
					f0f3f10.Name = resp.LaunchTemplateVersion.LaunchTemplateData.IamInstanceProfile.Name
				}
				f0f3.IAMInstanceProfile = f0f3f10
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.ImageId != nil {
				f0f3.ImageID = resp.LaunchTemplateVersion.LaunchTemplateData.ImageId
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.InstanceInitiatedShutdownBehavior != nil {
				f0f3.InstanceInitiatedShutdownBehavior = resp.LaunchTemplateVersion.LaunchTemplateData.InstanceInitiatedShutdownBehavior
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions != nil {
				f0f3f13 := &svcapitypes.LaunchTemplateInstanceMarketOptions{}
				if resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions.MarketType != nil {
					f0f3f13.MarketType = resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions.MarketType
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions.SpotOptions != nil {
					f0f3f13f1 := &svcapitypes.LaunchTemplateSpotMarketOptions{}
					if resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions.SpotOptions.BlockDurationMinutes != nil {
						f0f3f13f1.BlockDurationMinutes = resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions.SpotOptions.BlockDurationMinutes
					}
					if resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions.SpotOptions.InstanceInterruptionBehavior != nil {
						f0f3f13f1.InstanceInterruptionBehavior = resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions.SpotOptions.InstanceInterruptionBehavior
					}
					if resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions.SpotOptions.MaxPrice != nil {
						f0f3f13f1.MaxPrice = resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions.SpotOptions.MaxPrice
					}
					if resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions.SpotOptions.SpotInstanceType != nil {
						f0f3f13f1.SpotInstanceType = resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions.SpotOptions.SpotInstanceType
					}
					if resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions.SpotOptions.ValidUntil != nil {
						f0f3f13f1.ValidUntil = &metav1.Time{*resp.LaunchTemplateVersion.LaunchTemplateData.InstanceMarketOptions.SpotOptions.ValidUntil}
					}
					f0f3f13.SpotOptions = f0f3f13f1
				}
				f0f3.InstanceMarketOptions = f0f3f13
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.InstanceType != nil {
				f0f3.InstanceType = resp.LaunchTemplateVersion.LaunchTemplateData.InstanceType
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.KernelId != nil {
				f0f3.KernelID = resp.LaunchTemplateVersion.LaunchTemplateData.KernelId
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.KeyName != nil {
				f0f3.KeyName = resp.LaunchTemplateVersion.LaunchTemplateData.KeyName
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.LicenseSpecifications != nil {
				f0f3f17 := []*svcapitypes.LaunchTemplateLicenseConfiguration{}
				for _, f0f3f17iter := range resp.LaunchTemplateVersion.LaunchTemplateData.LicenseSpecifications {
					f0f3f17elem := &svcapitypes.LaunchTemplateLicenseConfiguration{}
					if f0f3f17iter.LicenseConfigurationArn != nil {
						f0f3f17elem.LicenseConfigurationARN = f0f3f17iter.LicenseConfigurationArn
					}
					f0f3f17 = append(f0f3f17, f0f3f17elem)
				}
				f0f3.LicenseSpecifications = f0f3f17
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.MetadataOptions != nil {
				f0f3f18 := &svcapitypes.LaunchTemplateInstanceMetadataOptions{}
				if resp.LaunchTemplateVersion.LaunchTemplateData.MetadataOptions.HttpEndpoint != nil {
					f0f3f18.HTTPEndpoint = resp.LaunchTemplateVersion.LaunchTemplateData.MetadataOptions.HttpEndpoint
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.MetadataOptions.HttpPutResponseHopLimit != nil {
					f0f3f18.HTTPPutResponseHopLimit = resp.LaunchTemplateVersion.LaunchTemplateData.MetadataOptions.HttpPutResponseHopLimit
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.MetadataOptions.HttpTokens != nil {
					f0f3f18.HTTPTokens = resp.LaunchTemplateVersion.LaunchTemplateData.MetadataOptions.HttpTokens
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.MetadataOptions.State != nil {
					f0f3f18.State = resp.LaunchTemplateVersion.LaunchTemplateData.MetadataOptions.State
				}
				f0f3.MetadataOptions = f0f3f18
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.Monitoring != nil {
				f0f3f19 := &svcapitypes.LaunchTemplatesMonitoring{}
				if resp.LaunchTemplateVersion.LaunchTemplateData.Monitoring.Enabled != nil {
					f0f3f19.Enabled = resp.LaunchTemplateVersion.LaunchTemplateData.Monitoring.Enabled
				}
				f0f3.Monitoring = f0f3f19
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.NetworkInterfaces != nil {
				f0f3f20 := []*svcapitypes.LaunchTemplateInstanceNetworkInterfaceSpecification{}
				for _, f0f3f20iter := range resp.LaunchTemplateVersion.LaunchTemplateData.NetworkInterfaces {
					f0f3f20elem := &svcapitypes.LaunchTemplateInstanceNetworkInterfaceSpecification{}
					if f0f3f20iter.AssociateCarrierIpAddress != nil {
						f0f3f20elem.AssociateCarrierIPAddress = f0f3f20iter.AssociateCarrierIpAddress
					}
					if f0f3f20iter.AssociatePublicIpAddress != nil {
						f0f3f20elem.AssociatePublicIPAddress = f0f3f20iter.AssociatePublicIpAddress
					}
					if f0f3f20iter.DeleteOnTermination != nil {
						f0f3f20elem.DeleteOnTermination = f0f3f20iter.DeleteOnTermination
					}
					if f0f3f20iter.Description != nil {
						f0f3f20elem.Description = f0f3f20iter.Description
					}
					if f0f3f20iter.DeviceIndex != nil {
						f0f3f20elem.DeviceIndex = f0f3f20iter.DeviceIndex
					}
					if f0f3f20iter.Groups != nil {
						f0f3f20elemf5 := []*string{}
						for _, f0f3f20elemf5iter := range f0f3f20iter.Groups {
							var f0f3f20elemf5elem string
							f0f3f20elemf5elem = *f0f3f20elemf5iter
							f0f3f20elemf5 = append(f0f3f20elemf5, &f0f3f20elemf5elem)
						}
						f0f3f20elem.Groups = f0f3f20elemf5
					}
					if f0f3f20iter.InterfaceType != nil {
						f0f3f20elem.InterfaceType = f0f3f20iter.InterfaceType
					}
					if f0f3f20iter.Ipv6AddressCount != nil {
						f0f3f20elem.IPv6AddressCount = f0f3f20iter.Ipv6AddressCount
					}
					if f0f3f20iter.Ipv6Addresses != nil {
						f0f3f20elemf8 := []*svcapitypes.InstanceIPv6Address{}
						for _, f0f3f20elemf8iter := range f0f3f20iter.Ipv6Addresses {
							f0f3f20elemf8elem := &svcapitypes.InstanceIPv6Address{}
							if f0f3f20elemf8iter.Ipv6Address != nil {
								f0f3f20elemf8elem.IPv6Address = f0f3f20elemf8iter.Ipv6Address
							}
							f0f3f20elemf8 = append(f0f3f20elemf8, f0f3f20elemf8elem)
						}
						f0f3f20elem.IPv6Addresses = f0f3f20elemf8
					}
					if f0f3f20iter.NetworkCardIndex != nil {
						f0f3f20elem.NetworkCardIndex = f0f3f20iter.NetworkCardIndex
					}
					if f0f3f20iter.NetworkInterfaceId != nil {
						f0f3f20elem.NetworkInterfaceID = f0f3f20iter.NetworkInterfaceId
					}
					if f0f3f20iter.PrivateIpAddress != nil {
						f0f3f20elem.PrivateIPAddress = f0f3f20iter.PrivateIpAddress
					}
					if f0f3f20iter.PrivateIpAddresses != nil {
						f0f3f20elemf12 := []*svcapitypes.PrivateIPAddressSpecification{}
						for _, f0f3f20elemf12iter := range f0f3f20iter.PrivateIpAddresses {
							f0f3f20elemf12elem := &svcapitypes.PrivateIPAddressSpecification{}
							if f0f3f20elemf12iter.Primary != nil {
								f0f3f20elemf12elem.Primary = f0f3f20elemf12iter.Primary
							}
							if f0f3f20elemf12iter.PrivateIpAddress != nil {
								f0f3f20elemf12elem.PrivateIPAddress = f0f3f20elemf12iter.PrivateIpAddress
							}
							f0f3f20elemf12 = append(f0f3f20elemf12, f0f3f20elemf12elem)
						}
						f0f3f20elem.PrivateIPAddresses = f0f3f20elemf12
					}
					if f0f3f20iter.SecondaryPrivateIpAddressCount != nil {
						f0f3f20elem.SecondaryPrivateIPAddressCount = f0f3f20iter.SecondaryPrivateIpAddressCount
					}
					if f0f3f20iter.SubnetId != nil {
						f0f3f20elem.SubnetID = f0f3f20iter.SubnetId
					}
					f0f3f20 = append(f0f3f20, f0f3f20elem)
				}
				f0f3.NetworkInterfaces = f0f3f20
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.Placement != nil {
				f0f3f21 := &svcapitypes.LaunchTemplatePlacement{}
				if resp.LaunchTemplateVersion.LaunchTemplateData.Placement.Affinity != nil {
					f0f3f21.Affinity = resp.LaunchTemplateVersion.LaunchTemplateData.Placement.Affinity
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.Placement.AvailabilityZone != nil {
					f0f3f21.AvailabilityZone = resp.LaunchTemplateVersion.LaunchTemplateData.Placement.AvailabilityZone
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.Placement.GroupName != nil {
					f0f3f21.GroupName = resp.LaunchTemplateVersion.LaunchTemplateData.Placement.GroupName
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.Placement.HostId != nil {
					f0f3f21.HostID = resp.LaunchTemplateVersion.LaunchTemplateData.Placement.HostId
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.Placement.HostResourceGroupArn != nil {
					f0f3f21.HostResourceGroupARN = resp.LaunchTemplateVersion.LaunchTemplateData.Placement.HostResourceGroupArn
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.Placement.PartitionNumber != nil {
					f0f3f21.PartitionNumber = resp.LaunchTemplateVersion.LaunchTemplateData.Placement.PartitionNumber
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.Placement.SpreadDomain != nil {
					f0f3f21.SpreadDomain = resp.LaunchTemplateVersion.LaunchTemplateData.Placement.SpreadDomain
				}
				if resp.LaunchTemplateVersion.LaunchTemplateData.Placement.Tenancy != nil {
					f0f3f21.Tenancy = resp.LaunchTemplateVersion.LaunchTemplateData.Placement.Tenancy
				}
				f0f3.Placement = f0f3f21
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.RamDiskId != nil {
				f0f3.RamDiskID = resp.LaunchTemplateVersion.LaunchTemplateData.RamDiskId
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.SecurityGroupIds != nil {
				f0f3f23 := []*string{}
				for _, f0f3f23iter := range resp.LaunchTemplateVersion.LaunchTemplateData.SecurityGroupIds {
					var f0f3f23elem string
					f0f3f23elem = *f0f3f23iter
					f0f3f23 = append(f0f3f23, &f0f3f23elem)
				}
				f0f3.SecurityGroupIDs = f0f3f23
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.SecurityGroups != nil {
				f0f3f24 := []*string{}
				for _, f0f3f24iter := range resp.LaunchTemplateVersion.LaunchTemplateData.SecurityGroups {
					var f0f3f24elem string
					f0f3f24elem = *f0f3f24iter
					f0f3f24 = append(f0f3f24, &f0f3f24elem)
				}
				f0f3.SecurityGroups = f0f3f24
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.TagSpecifications != nil {
				f0f3f25 := []*svcapitypes.LaunchTemplateTagSpecification{}
				for _, f0f3f25iter := range resp.LaunchTemplateVersion.LaunchTemplateData.TagSpecifications {
					f0f3f25elem := &svcapitypes.LaunchTemplateTagSpecification{}
					if f0f3f25iter.ResourceType != nil {
						f0f3f25elem.ResourceType = f0f3f25iter.ResourceType
					}
					if f0f3f25iter.Tags != nil {
						f0f3f25elemf1 := []*svcapitypes.Tag{}
						for _, f0f3f25elemf1iter := range f0f3f25iter.Tags {
							f0f3f25elemf1elem := &svcapitypes.Tag{}
							if f0f3f25elemf1iter.Key != nil {
								f0f3f25elemf1elem.Key = f0f3f25elemf1iter.Key
							}
							if f0f3f25elemf1iter.Value != nil {
								f0f3f25elemf1elem.Value = f0f3f25elemf1iter.Value
							}
							f0f3f25elemf1 = append(f0f3f25elemf1, f0f3f25elemf1elem)
						}
						f0f3f25elem.Tags = f0f3f25elemf1
					}
					f0f3f25 = append(f0f3f25, f0f3f25elem)
				}
				f0f3.TagSpecifications = f0f3f25
			}
			if resp.LaunchTemplateVersion.LaunchTemplateData.UserData != nil {
				f0f3.UserData = resp.LaunchTemplateVersion.LaunchTemplateData.UserData
			}
			f0.LaunchTemplateData = f0f3
		}
		if resp.LaunchTemplateVersion.LaunchTemplateId != nil {
			f0.LaunchTemplateID = resp.LaunchTemplateVersion.LaunchTemplateId
		}
		if resp.LaunchTemplateVersion.LaunchTemplateName != nil {
			f0.LaunchTemplateName = resp.LaunchTemplateVersion.LaunchTemplateName
		}
		if resp.LaunchTemplateVersion.VersionDescription != nil {
			f0.VersionDescription = resp.LaunchTemplateVersion.VersionDescription
		}
		if resp.LaunchTemplateVersion.VersionNumber != nil {
			f0.VersionNumber = resp.LaunchTemplateVersion.VersionNumber
		}
		ko.Status.LaunchTemplateVersion = f0
	}
	if resp.Warning != nil {
		f1 := &svcapitypes.ValidationWarning{}
		if resp.Warning.Errors != nil {
			f1f0 := []*svcapitypes.ValidationError{}
			for _, f1f0iter := range resp.Warning.Errors {
				f1f0elem := &svcapitypes.ValidationError{}
				if f1f0iter.Code != nil {
					f1f0elem.Code = f1f0iter.Code
				}
				if f1f0iter.Message != nil {
					f1f0elem.Message = f1f0iter.Message
				}
				f1f0 = append(f1f0, f1f0elem)
			}
			f1.Errors = f1f0
		}
		ko.Status.Warning = f1
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateLaunchTemplateVersionInput, error) {
	res := &svcsdk.CreateLaunchTemplateVersionInput{}

	if r.ko.Spec.ClientToken != nil {
		res.SetClientToken(*r.ko.Spec.ClientToken)
	}
	if r.ko.Spec.DryRun != nil {
		res.SetDryRun(*r.ko.Spec.DryRun)
	}
	if r.ko.Spec.LaunchTemplateData != nil {
		f2 := &svcsdk.RequestLaunchTemplateData{}
		if r.ko.Spec.LaunchTemplateData.BlockDeviceMappings != nil {
			f2f0 := []*svcsdk.LaunchTemplateBlockDeviceMappingRequest{}
			for _, f2f0iter := range r.ko.Spec.LaunchTemplateData.BlockDeviceMappings {
				f2f0elem := &svcsdk.LaunchTemplateBlockDeviceMappingRequest{}
				if f2f0iter.DeviceName != nil {
					f2f0elem.SetDeviceName(*f2f0iter.DeviceName)
				}
				if f2f0iter.EBS != nil {
					f2f0elemf1 := &svcsdk.LaunchTemplateEbsBlockDeviceRequest{}
					if f2f0iter.EBS.DeleteOnTermination != nil {
						f2f0elemf1.SetDeleteOnTermination(*f2f0iter.EBS.DeleteOnTermination)
					}
					if f2f0iter.EBS.Encrypted != nil {
						f2f0elemf1.SetEncrypted(*f2f0iter.EBS.Encrypted)
					}
					if f2f0iter.EBS.IOPS != nil {
						f2f0elemf1.SetIops(*f2f0iter.EBS.IOPS)
					}
					if f2f0iter.EBS.KMSKeyID != nil {
						f2f0elemf1.SetKmsKeyId(*f2f0iter.EBS.KMSKeyID)
					}
					if f2f0iter.EBS.SnapshotID != nil {
						f2f0elemf1.SetSnapshotId(*f2f0iter.EBS.SnapshotID)
					}
					if f2f0iter.EBS.Throughput != nil {
						f2f0elemf1.SetThroughput(*f2f0iter.EBS.Throughput)
					}
					if f2f0iter.EBS.VolumeSize != nil {
						f2f0elemf1.SetVolumeSize(*f2f0iter.EBS.VolumeSize)
					}
					if f2f0iter.EBS.VolumeType != nil {
						f2f0elemf1.SetVolumeType(*f2f0iter.EBS.VolumeType)
					}
					f2f0elem.SetEbs(f2f0elemf1)
				}
				if f2f0iter.NoDevice != nil {
					f2f0elem.SetNoDevice(*f2f0iter.NoDevice)
				}
				if f2f0iter.VirtualName != nil {
					f2f0elem.SetVirtualName(*f2f0iter.VirtualName)
				}
				f2f0 = append(f2f0, f2f0elem)
			}
			f2.SetBlockDeviceMappings(f2f0)
		}
		if r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification != nil {
			f2f1 := &svcsdk.LaunchTemplateCapacityReservationSpecificationRequest{}
			if r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationPreference != nil {
				f2f1.SetCapacityReservationPreference(*r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationPreference)
			}
			if r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget != nil {
				f2f1f1 := &svcsdk.CapacityReservationTarget{}
				if r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationID != nil {
					f2f1f1.SetCapacityReservationId(*r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationID)
				}
				if r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARN != nil {
					f2f1f1.SetCapacityReservationResourceGroupArn(*r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARN)
				}
				f2f1.SetCapacityReservationTarget(f2f1f1)
			}
			f2.SetCapacityReservationSpecification(f2f1)
		}
		if r.ko.Spec.LaunchTemplateData.CPUOptions != nil {
			f2f2 := &svcsdk.LaunchTemplateCpuOptionsRequest{}
			if r.ko.Spec.LaunchTemplateData.CPUOptions.CoreCount != nil {
				f2f2.SetCoreCount(*r.ko.Spec.LaunchTemplateData.CPUOptions.CoreCount)
			}
			if r.ko.Spec.LaunchTemplateData.CPUOptions.ThreadsPerCore != nil {
				f2f2.SetThreadsPerCore(*r.ko.Spec.LaunchTemplateData.CPUOptions.ThreadsPerCore)
			}
			f2.SetCpuOptions(f2f2)
		}
		if r.ko.Spec.LaunchTemplateData.CreditSpecification != nil {
			f2f3 := &svcsdk.CreditSpecificationRequest{}
			if r.ko.Spec.LaunchTemplateData.CreditSpecification.CPUCredits != nil {
				f2f3.SetCpuCredits(*r.ko.Spec.LaunchTemplateData.CreditSpecification.CPUCredits)
			}
			f2.SetCreditSpecification(f2f3)
		}
		if r.ko.Spec.LaunchTemplateData.DisableAPITermination != nil {
			f2.SetDisableApiTermination(*r.ko.Spec.LaunchTemplateData.DisableAPITermination)
		}
		if r.ko.Spec.LaunchTemplateData.EBSOptimized != nil {
			f2.SetEbsOptimized(*r.ko.Spec.LaunchTemplateData.EBSOptimized)
		}
		if r.ko.Spec.LaunchTemplateData.ElasticGPUSpecifications != nil {
			f2f6 := []*svcsdk.ElasticGpuSpecification{}
			for _, f2f6iter := range r.ko.Spec.LaunchTemplateData.ElasticGPUSpecifications {
				f2f6elem := &svcsdk.ElasticGpuSpecification{}
				if f2f6iter.Type != nil {
					f2f6elem.SetType(*f2f6iter.Type)
				}
				f2f6 = append(f2f6, f2f6elem)
			}
			f2.SetElasticGpuSpecifications(f2f6)
		}
		if r.ko.Spec.LaunchTemplateData.ElasticInferenceAccelerators != nil {
			f2f7 := []*svcsdk.LaunchTemplateElasticInferenceAccelerator{}
			for _, f2f7iter := range r.ko.Spec.LaunchTemplateData.ElasticInferenceAccelerators {
				f2f7elem := &svcsdk.LaunchTemplateElasticInferenceAccelerator{}
				if f2f7iter.Count != nil {
					f2f7elem.SetCount(*f2f7iter.Count)
				}
				if f2f7iter.Type != nil {
					f2f7elem.SetType(*f2f7iter.Type)
				}
				f2f7 = append(f2f7, f2f7elem)
			}
			f2.SetElasticInferenceAccelerators(f2f7)
		}
		if r.ko.Spec.LaunchTemplateData.EnclaveOptions != nil {
			f2f8 := &svcsdk.LaunchTemplateEnclaveOptionsRequest{}
			if r.ko.Spec.LaunchTemplateData.EnclaveOptions.Enabled != nil {
				f2f8.SetEnabled(*r.ko.Spec.LaunchTemplateData.EnclaveOptions.Enabled)
			}
			f2.SetEnclaveOptions(f2f8)
		}
		if r.ko.Spec.LaunchTemplateData.HibernationOptions != nil {
			f2f9 := &svcsdk.LaunchTemplateHibernationOptionsRequest{}
			if r.ko.Spec.LaunchTemplateData.HibernationOptions.Configured != nil {
				f2f9.SetConfigured(*r.ko.Spec.LaunchTemplateData.HibernationOptions.Configured)
			}
			f2.SetHibernationOptions(f2f9)
		}
		if r.ko.Spec.LaunchTemplateData.IAMInstanceProfile != nil {
			f2f10 := &svcsdk.LaunchTemplateIamInstanceProfileSpecificationRequest{}
			if r.ko.Spec.LaunchTemplateData.IAMInstanceProfile.ARN != nil {
				f2f10.SetArn(*r.ko.Spec.LaunchTemplateData.IAMInstanceProfile.ARN)
			}
			if r.ko.Spec.LaunchTemplateData.IAMInstanceProfile.Name != nil {
				f2f10.SetName(*r.ko.Spec.LaunchTemplateData.IAMInstanceProfile.Name)
			}
			f2.SetIamInstanceProfile(f2f10)
		}
		if r.ko.Spec.LaunchTemplateData.ImageID != nil {
			f2.SetImageId(*r.ko.Spec.LaunchTemplateData.ImageID)
		}
		if r.ko.Spec.LaunchTemplateData.InstanceInitiatedShutdownBehavior != nil {
			f2.SetInstanceInitiatedShutdownBehavior(*r.ko.Spec.LaunchTemplateData.InstanceInitiatedShutdownBehavior)
		}
		if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions != nil {
			f2f13 := &svcsdk.LaunchTemplateInstanceMarketOptionsRequest{}
			if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.MarketType != nil {
				f2f13.SetMarketType(*r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.MarketType)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions != nil {
				f2f13f1 := &svcsdk.LaunchTemplateSpotMarketOptionsRequest{}
				if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.BlockDurationMinutes != nil {
					f2f13f1.SetBlockDurationMinutes(*r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.BlockDurationMinutes)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.InstanceInterruptionBehavior != nil {
					f2f13f1.SetInstanceInterruptionBehavior(*r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.InstanceInterruptionBehavior)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.MaxPrice != nil {
					f2f13f1.SetMaxPrice(*r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.MaxPrice)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.SpotInstanceType != nil {
					f2f13f1.SetSpotInstanceType(*r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.SpotInstanceType)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.ValidUntil != nil {
					f2f13f1.SetValidUntil(r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.ValidUntil.Time)
				}
				f2f13.SetSpotOptions(f2f13f1)
			}
			f2.SetInstanceMarketOptions(f2f13)
		}
		if r.ko.Spec.LaunchTemplateData.InstanceType != nil {
			f2.SetInstanceType(*r.ko.Spec.LaunchTemplateData.InstanceType)
		}
		if r.ko.Spec.LaunchTemplateData.KernelID != nil {
			f2.SetKernelId(*r.ko.Spec.LaunchTemplateData.KernelID)
		}
		if r.ko.Spec.LaunchTemplateData.KeyName != nil {
			f2.SetKeyName(*r.ko.Spec.LaunchTemplateData.KeyName)
		}
		if r.ko.Spec.LaunchTemplateData.LicenseSpecifications != nil {
			f2f17 := []*svcsdk.LaunchTemplateLicenseConfigurationRequest{}
			for _, f2f17iter := range r.ko.Spec.LaunchTemplateData.LicenseSpecifications {
				f2f17elem := &svcsdk.LaunchTemplateLicenseConfigurationRequest{}
				if f2f17iter.LicenseConfigurationARN != nil {
					f2f17elem.SetLicenseConfigurationArn(*f2f17iter.LicenseConfigurationARN)
				}
				f2f17 = append(f2f17, f2f17elem)
			}
			f2.SetLicenseSpecifications(f2f17)
		}
		if r.ko.Spec.LaunchTemplateData.MetadataOptions != nil {
			f2f18 := &svcsdk.LaunchTemplateInstanceMetadataOptionsRequest{}
			if r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPEndpoint != nil {
				f2f18.SetHttpEndpoint(*r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPEndpoint)
			}
			if r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPPutResponseHopLimit != nil {
				f2f18.SetHttpPutResponseHopLimit(*r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPPutResponseHopLimit)
			}
			if r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPTokens != nil {
				f2f18.SetHttpTokens(*r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPTokens)
			}
			f2.SetMetadataOptions(f2f18)
		}
		if r.ko.Spec.LaunchTemplateData.Monitoring != nil {
			f2f19 := &svcsdk.LaunchTemplatesMonitoringRequest{}
			if r.ko.Spec.LaunchTemplateData.Monitoring.Enabled != nil {
				f2f19.SetEnabled(*r.ko.Spec.LaunchTemplateData.Monitoring.Enabled)
			}
			f2.SetMonitoring(f2f19)
		}
		if r.ko.Spec.LaunchTemplateData.NetworkInterfaces != nil {
			f2f20 := []*svcsdk.LaunchTemplateInstanceNetworkInterfaceSpecificationRequest{}
			for _, f2f20iter := range r.ko.Spec.LaunchTemplateData.NetworkInterfaces {
				f2f20elem := &svcsdk.LaunchTemplateInstanceNetworkInterfaceSpecificationRequest{}
				if f2f20iter.AssociateCarrierIPAddress != nil {
					f2f20elem.SetAssociateCarrierIpAddress(*f2f20iter.AssociateCarrierIPAddress)
				}
				if f2f20iter.AssociatePublicIPAddress != nil {
					f2f20elem.SetAssociatePublicIpAddress(*f2f20iter.AssociatePublicIPAddress)
				}
				if f2f20iter.DeleteOnTermination != nil {
					f2f20elem.SetDeleteOnTermination(*f2f20iter.DeleteOnTermination)
				}
				if f2f20iter.Description != nil {
					f2f20elem.SetDescription(*f2f20iter.Description)
				}
				if f2f20iter.DeviceIndex != nil {
					f2f20elem.SetDeviceIndex(*f2f20iter.DeviceIndex)
				}
				if f2f20iter.Groups != nil {
					f2f20elemf5 := []*string{}
					for _, f2f20elemf5iter := range f2f20iter.Groups {
						var f2f20elemf5elem string
						f2f20elemf5elem = *f2f20elemf5iter
						f2f20elemf5 = append(f2f20elemf5, &f2f20elemf5elem)
					}
					f2f20elem.SetGroups(f2f20elemf5)
				}
				if f2f20iter.InterfaceType != nil {
					f2f20elem.SetInterfaceType(*f2f20iter.InterfaceType)
				}
				if f2f20iter.IPv6AddressCount != nil {
					f2f20elem.SetIpv6AddressCount(*f2f20iter.IPv6AddressCount)
				}
				if f2f20iter.IPv6Addresses != nil {
					f2f20elemf8 := []*svcsdk.InstanceIpv6AddressRequest{}
					for _, f2f20elemf8iter := range f2f20iter.IPv6Addresses {
						f2f20elemf8elem := &svcsdk.InstanceIpv6AddressRequest{}
						if f2f20elemf8iter.IPv6Address != nil {
							f2f20elemf8elem.SetIpv6Address(*f2f20elemf8iter.IPv6Address)
						}
						f2f20elemf8 = append(f2f20elemf8, f2f20elemf8elem)
					}
					f2f20elem.SetIpv6Addresses(f2f20elemf8)
				}
				if f2f20iter.NetworkCardIndex != nil {
					f2f20elem.SetNetworkCardIndex(*f2f20iter.NetworkCardIndex)
				}
				if f2f20iter.NetworkInterfaceID != nil {
					f2f20elem.SetNetworkInterfaceId(*f2f20iter.NetworkInterfaceID)
				}
				if f2f20iter.PrivateIPAddress != nil {
					f2f20elem.SetPrivateIpAddress(*f2f20iter.PrivateIPAddress)
				}
				if f2f20iter.PrivateIPAddresses != nil {
					f2f20elemf12 := []*svcsdk.PrivateIpAddressSpecification{}
					for _, f2f20elemf12iter := range f2f20iter.PrivateIPAddresses {
						f2f20elemf12elem := &svcsdk.PrivateIpAddressSpecification{}
						if f2f20elemf12iter.Primary != nil {
							f2f20elemf12elem.SetPrimary(*f2f20elemf12iter.Primary)
						}
						if f2f20elemf12iter.PrivateIPAddress != nil {
							f2f20elemf12elem.SetPrivateIpAddress(*f2f20elemf12iter.PrivateIPAddress)
						}
						f2f20elemf12 = append(f2f20elemf12, f2f20elemf12elem)
					}
					f2f20elem.SetPrivateIpAddresses(f2f20elemf12)
				}
				if f2f20iter.SecondaryPrivateIPAddressCount != nil {
					f2f20elem.SetSecondaryPrivateIpAddressCount(*f2f20iter.SecondaryPrivateIPAddressCount)
				}
				if f2f20iter.SubnetID != nil {
					f2f20elem.SetSubnetId(*f2f20iter.SubnetID)
				}
				f2f20 = append(f2f20, f2f20elem)
			}
			f2.SetNetworkInterfaces(f2f20)
		}
		if r.ko.Spec.LaunchTemplateData.Placement != nil {
			f2f21 := &svcsdk.LaunchTemplatePlacementRequest{}
			if r.ko.Spec.LaunchTemplateData.Placement.Affinity != nil {
				f2f21.SetAffinity(*r.ko.Spec.LaunchTemplateData.Placement.Affinity)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.AvailabilityZone != nil {
				f2f21.SetAvailabilityZone(*r.ko.Spec.LaunchTemplateData.Placement.AvailabilityZone)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.GroupName != nil {
				f2f21.SetGroupName(*r.ko.Spec.LaunchTemplateData.Placement.GroupName)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.HostID != nil {
				f2f21.SetHostId(*r.ko.Spec.LaunchTemplateData.Placement.HostID)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.HostResourceGroupARN != nil {
				f2f21.SetHostResourceGroupArn(*r.ko.Spec.LaunchTemplateData.Placement.HostResourceGroupARN)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.PartitionNumber != nil {
				f2f21.SetPartitionNumber(*r.ko.Spec.LaunchTemplateData.Placement.PartitionNumber)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.SpreadDomain != nil {
				f2f21.SetSpreadDomain(*r.ko.Spec.LaunchTemplateData.Placement.SpreadDomain)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.Tenancy != nil {
				f2f21.SetTenancy(*r.ko.Spec.LaunchTemplateData.Placement.Tenancy)
			}
			f2.SetPlacement(f2f21)
		}
		if r.ko.Spec.LaunchTemplateData.RamDiskID != nil {
			f2.SetRamDiskId(*r.ko.Spec.LaunchTemplateData.RamDiskID)
		}
		if r.ko.Spec.LaunchTemplateData.SecurityGroupIDs != nil {
			f2f23 := []*string{}
			for _, f2f23iter := range r.ko.Spec.LaunchTemplateData.SecurityGroupIDs {
				var f2f23elem string
				f2f23elem = *f2f23iter
				f2f23 = append(f2f23, &f2f23elem)
			}
			f2.SetSecurityGroupIds(f2f23)
		}
		if r.ko.Spec.LaunchTemplateData.SecurityGroups != nil {
			f2f24 := []*string{}
			for _, f2f24iter := range r.ko.Spec.LaunchTemplateData.SecurityGroups {
				var f2f24elem string
				f2f24elem = *f2f24iter
				f2f24 = append(f2f24, &f2f24elem)
			}
			f2.SetSecurityGroups(f2f24)
		}
		if r.ko.Spec.LaunchTemplateData.TagSpecifications != nil {
			f2f25 := []*svcsdk.LaunchTemplateTagSpecificationRequest{}
			for _, f2f25iter := range r.ko.Spec.LaunchTemplateData.TagSpecifications {
				f2f25elem := &svcsdk.LaunchTemplateTagSpecificationRequest{}
				if f2f25iter.ResourceType != nil {
					f2f25elem.SetResourceType(*f2f25iter.ResourceType)
				}
				if f2f25iter.Tags != nil {
					f2f25elemf1 := []*svcsdk.Tag{}
					for _, f2f25elemf1iter := range f2f25iter.Tags {
						f2f25elemf1elem := &svcsdk.Tag{}
						if f2f25elemf1iter.Key != nil {
							f2f25elemf1elem.SetKey(*f2f25elemf1iter.Key)
						}
						if f2f25elemf1iter.Value != nil {
							f2f25elemf1elem.SetValue(*f2f25elemf1iter.Value)
						}
						f2f25elemf1 = append(f2f25elemf1, f2f25elemf1elem)
					}
					f2f25elem.SetTags(f2f25elemf1)
				}
				f2f25 = append(f2f25, f2f25elem)
			}
			f2.SetTagSpecifications(f2f25)
		}
		if r.ko.Spec.LaunchTemplateData.UserData != nil {
			f2.SetUserData(*r.ko.Spec.LaunchTemplateData.UserData)
		}
		res.SetLaunchTemplateData(f2)
	}
	if r.ko.Spec.LaunchTemplateID != nil {
		res.SetLaunchTemplateId(*r.ko.Spec.LaunchTemplateID)
	}
	if r.ko.Spec.LaunchTemplateName != nil {
		res.SetLaunchTemplateName(*r.ko.Spec.LaunchTemplateName)
	}
	if r.ko.Spec.SourceVersion != nil {
		res.SetSourceVersion(*r.ko.Spec.SourceVersion)
	}
	if r.ko.Spec.VersionDescription != nil {
		res.SetVersionDescription(*r.ko.Spec.VersionDescription)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	diffReporter *ackcompare.Reporter,
) (*resource, error) {
	// TODO(jaypipes): Figure this out...
	return nil, ackerr.NotImplemented
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) error {
	// TODO(jaypipes): Figure this out...
	return nil

}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.LaunchTemplateVersion,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
			break
		}
	}

	if rm.terminalAWSError(err) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		terminalCondition.Status = corev1.ConditionTrue
		awsErr, _ := ackerr.AWSError(err)
		errorMessage := awsErr.Message()
		terminalCondition.Message = &errorMessage
	} else if terminalCondition != nil {
		terminalCondition.Status = corev1.ConditionFalse
		terminalCondition.Message = nil
	}
	if terminalCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
